# Generated by Django 6.0.5 on 2026-07-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opc', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='opcdiagram',
            new_name='opc_opcdiag_part_co_b74b3d_idx',
            old_name='opc_opcdiag_part_co_dca32e_idx',
        ),
        migrations.RenameIndex(
            model_name='opcdiagram',
            new_name='opc_opcdiag_updated_6b3c8e_idx',
            old_name='opc_opcdiag_updated_95a29f_idx',
        ),
        migrations.RenameIndex(
            model_name='opcedge',
            new_name='opc_opcedge_diagram_f7f84c_idx',
            old_name='opc_opcedge_diagram_83770d_idx',
        ),
        migrations.RenameIndex(
            model_name='opcnode',
            new_name='opc_opcnode_diagram_d93434_idx',
            old_name='opc_opcnode_diagram_8193d1_idx',
        ),
        migrations.RenameIndex(
            model_name='opcnode',
            new_name='opc_opcnode_node_ty_6cbfea_idx',
            old_name='opc_opcnode_node_ty_1f8d92_idx',
        ),
    ]
