# Generated by Django 6.0.6 on 2026-07-18 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_items', '0003_bom_bomrevision_bomline_and_more'),
        ('opc', '0002_rename_opc_opcdiag_part_co_dca32e_idx_opc_opcdiag_part_co_b74b3d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opcdiagram',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opcdiagram',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_opc_diagrams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opcdiagram',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opcdiagram',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opcdiagram',
            name='item_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opc_diagrams', to='enterprise_items.itemrevision'),
        ),
        migrations.AddField(
            model_name='opcdiagram',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opcdiagram',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_opc_diagrams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opcdiagram',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opcdiagram',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_opc_diagrams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opcdiagram',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opcdiagram',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='opc.opcdiagram'),
        ),
        migrations.AddField(
            model_name='opcnode',
            name='buffer_time_hours',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='opcnode',
            name='execution_type',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External'), ('INSPECTION', 'Inspection'), ('TRANSPORT', 'Transport'), ('MIXED', 'Mixed')], default='INTERNAL', max_length=20),
        ),
        migrations.AddField(
            model_name='opcnode',
            name='external_lead_time_days',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='opcnode',
            name='inspection_time_hours',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='opcnode',
            name='move_time_hours',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='opcnode',
            name='queue_time_hours',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='opcnode',
            name='run_time_per_unit_hours',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='opcnode',
            name='setup_time_hours',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='opcdiagram',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('RELEASED', 'Released'), ('SUPERSEDED', 'Superseded'), ('OBSOLETE', 'Obsolete'), ('ACTIVE', 'Active (legacy)'), ('ARCHIVED', 'Archived (legacy)')], default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='opcdiagram',
            index=models.Index(fields=['item_revision', 'status'], name='opc_opcdiag_item_re_e217db_idx'),
        ),
    ]
