# Generated by Django 6.0.6 on 2026-07-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_items', '0003_bom_bomrevision_bomline_and_more'),
        ('opc', '0003_opcdiagram_approved_at_opcdiagram_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='opcdiagram',
            unique_together={('item_revision', 'revision')},
        ),
    ]
