# Generated by Django 6.0.6 on 2026-07-28 13:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opc', '0005_opcdiagram_graph_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('machine_type', models.CharField(blank=True, max_length=120)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['asset_code'],
            },
        ),
        migrations.AddField(
            model_name='opcnode',
            name='operation_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opcnode',
            name='machine_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opc_nodes', to='opc.machineasset'),
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['active', 'code'], name='opc_plant_active_74dc50_idx')],
            },
        ),
        migrations.AddField(
            model_name='machineasset',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_assets', to='opc.plant'),
        ),
        migrations.AddField(
            model_name='opcnode',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opc_nodes', to='opc.plant'),
        ),
        migrations.CreateModel(
            name='ProcessDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process_code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('execution_classification', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External'), ('FLEXIBLE', 'Internal or external')], default='INTERNAL', max_length=20)),
                ('default_setup_time_hours', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('default_run_time_per_unit_hours', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('special_process', models.BooleanField(default=False)),
                ('inspection_required', models.BooleanField(default=False)),
                ('preferred_work_center_category', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['process_code'],
                'indexes': [models.Index(fields=['active', 'execution_classification'], name='opc_process_active_8b58ea_idx')],
            },
        ),
        migrations.AddField(
            model_name='opcnode',
            name='process_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opc_nodes', to='opc.processdefinition'),
        ),
        migrations.CreateModel(
            name='ToolingDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tooling_code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('FIXTURE', 'Fixture'), ('GAUGE', 'Gauge'), ('CUTTER', 'Cutter'), ('DIE', 'Die'), ('OTHER', 'Other')], default='FIXTURE', max_length=20)),
                ('reusable', models.BooleanField(default=True)),
                ('consumable', models.BooleanField(default=False)),
                ('calibration_required', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tooling_code'],
                'indexes': [models.Index(fields=['active', 'category'], name='opc_tooling_active_7f0748_idx')],
            },
        ),
        migrations.CreateModel(
            name='OPCToolingRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('mandatory', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooling_requirements', to='opc.opcnode')),
                ('tooling_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opc_requirements', to='opc.toolingdefinition')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('capacity_classification', models.CharField(choices=[('GENERAL', 'General'), ('MANUAL', 'Manual'), ('MACHINE', 'Machine'), ('OUTSOURCE', 'Outsource coordination')], default='GENERAL', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_centers', to='opc.plant')),
            ],
            options={
                'ordering': ['plant__code', 'code'],
            },
        ),
        migrations.AddField(
            model_name='machineasset',
            name='work_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_assets', to='opc.workcenter'),
        ),
        migrations.AddField(
            model_name='opcnode',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opc_nodes', to='opc.workcenter'),
        ),
        migrations.AddIndex(
            model_name='opcnode',
            index=models.Index(fields=['diagram', 'operation_number'], name='opc_opcnode_diagram_d10cbd_idx'),
        ),
        migrations.AddConstraint(
            model_name='opcnode',
            constraint=models.UniqueConstraint(condition=models.Q(('operation_number__isnull', False)), fields=('diagram', 'operation_number'), name='opc_unique_operation_number_per_diagram'),
        ),
        migrations.AddIndex(
            model_name='opctoolingrequirement',
            index=models.Index(fields=['node', 'sequence'], name='opc_opctool_node_id_1056c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='opctoolingrequirement',
            unique_together={('node', 'tooling_definition')},
        ),
        migrations.AddIndex(
            model_name='workcenter',
            index=models.Index(fields=['plant', 'active'], name='opc_workcen_plant_i_ee4051_idx'),
        ),
        migrations.AddIndex(
            model_name='workcenter',
            index=models.Index(fields=['code'], name='opc_workcen_code_a8cffb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workcenter',
            unique_together={('plant', 'code')},
        ),
        migrations.AddIndex(
            model_name='machineasset',
            index=models.Index(fields=['plant', 'work_center', 'active'], name='opc_machine_plant_i_a55925_idx'),
        ),
    ]
