# Generated by Django 6.0.5 on 2026-07-28 13:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opc', '0006_machineasset_opcnode_operation_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OPCValidationEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('graph_version', models.PositiveBigIntegerField()),
                ('policy_version', models.CharField(max_length=80)),
                ('mode', models.CharField(choices=[('draft', 'Draft'), ('release', 'Release')], default='release', max_length=20)),
                ('validated_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('valid', models.BooleanField(default=False)),
                ('release_ready', models.BooleanField(default=False)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('acknowledged_issue_keys', models.JSONField(blank=True, default=list)),
                ('acknowledged_warning_codes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opc_validation_evidence', to=settings.AUTH_USER_MODEL)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_evidence', to='opc.opcdiagram')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['diagram', 'graph_version', 'policy_version'], name='opc_opcvali_diagram_7f6015_idx'), models.Index(fields=['released_at'], name='opc_opcvali_release_333c25_idx')],
            },
        ),
    ]
