# Generated by Django 6.0.6 on 2026-07-29 04:29

import django.db.models.deletion
import ktcPlanning.validators
import opc.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_items', '0008_remove_sequencedefinition_uniq_sequence_scope_per_version_and_more'),
        ('opc', '0007_opcvalidationevidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opcdiagram',
            name='manufacturing_bom_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opc_diagrams', to='enterprise_items.bomrevision'),
        ),
        migrations.CreateModel(
            name='ControlledDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('DRAWING', 'Drawing'), ('SPECIFICATION', 'Specification'), ('WORK_INSTRUCTION', 'Work instruction'), ('INSPECTION_INSTRUCTION', 'Inspection instruction'), ('PROCESS_SHEET', 'Process sheet'), ('SAFETY_INSTRUCTION', 'Safety instruction'), ('TOOLING_INSTRUCTION', 'Tooling instruction'), ('CERTIFICATE_TEMPLATE', 'Certificate template'), ('OTHER', 'Other')], default='OTHER', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('owner_department', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_controlled_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_number'],
            },
        ),
        migrations.CreateModel(
            name='ControlledDocumentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('RELEASED', 'Released'), ('SUPERSEDED', 'Superseded'), ('OBSOLETE', 'Obsolete')], default='DRAFT', max_length=20)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to=opc.models.controlled_document_upload_to, validators=[ktcPlanning.validators.ChatFileValidator()])),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('change_summary', models.TextField(blank=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_controlled_document_revisions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='opc.controlleddocument')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_controlled_document_revisions', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='opc.controlleddocumentrevision')),
            ],
            options={
                'ordering': ['document__document_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngineeringChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_number', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_engineering_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngineeringChangeOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_number', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('IMPLEMENTED', 'Implemented'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('effectivity_date', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('implemented_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_engineering_change_orders', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='opc.engineeringchangerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngineeringChangeObjectLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(choices=[('ITEM_REVISION', 'Item revision'), ('BOM_REVISION', 'BOM revision'), ('OPC_DIAGRAM', 'OPC diagram'), ('DOCUMENT_REVISION', 'Document revision')], max_length=40)),
                ('object_id', models.UUIDField()),
                ('role', models.CharField(choices=[('AFFECTED', 'Affected'), ('REPLACEMENT', 'Replacement'), ('REFERENCE', 'Reference')], default='AFFECTED', max_length=20)),
                ('before_object_type', models.CharField(blank=True, choices=[('ITEM_REVISION', 'Item revision'), ('BOM_REVISION', 'BOM revision'), ('OPC_DIAGRAM', 'OPC diagram'), ('DOCUMENT_REVISION', 'Document revision')], max_length=40)),
                ('before_object_id', models.UUIDField(blank=True, null=True)),
                ('after_object_type', models.CharField(blank=True, choices=[('ITEM_REVISION', 'Item revision'), ('BOM_REVISION', 'BOM revision'), ('OPC_DIAGRAM', 'OPC diagram'), ('DOCUMENT_REVISION', 'Document revision')], max_length=40)),
                ('after_object_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_links', to='opc.engineeringchangeorder')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_links', to='opc.engineeringchangerequest')),
            ],
            options={
                'ordering': ['object_type', 'object_id', 'role'],
            },
        ),
        migrations.CreateModel(
            name='OPCNodeDocumentRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('WORK_INSTRUCTION', 'Work instruction'), ('DRAWING', 'Drawing'), ('SPECIFICATION', 'Specification'), ('INSPECTION', 'Inspection'), ('PROCESS_SHEET', 'Process sheet'), ('SAFETY', 'Safety'), ('OTHER', 'Other')], default='WORK_INSTRUCTION', max_length=40)),
                ('mandatory', models.BooleanField(default=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opc_node_requirements', to='opc.controlleddocumentrevision')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='opc.opcnode')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OPCOperationMaterialAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit', models.CharField(default='EA', max_length=30)),
                ('scrap_percent', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('allocation_type', models.CharField(choices=[('CONSUME', 'Consume'), ('ISSUE', 'Issue'), ('ASSEMBLE', 'Assemble'), ('SUPPLIED', 'Supplied'), ('CONSUMABLE', 'Consumable')], default='CONSUME', max_length=20)),
                ('issue_at_operation', models.BooleanField(default=True)),
                ('backflush', models.BooleanField(default=False)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opc_allocations', to='enterprise_items.bomline')),
                ('component_item_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opc_material_allocations', to='enterprise_items.itemrevision')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_allocations', to='opc.opcnode')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='controlleddocument',
            index=models.Index(fields=['document_type', 'active'], name='opc_control_documen_a40e11_idx'),
        ),
        migrations.AddIndex(
            model_name='controlleddocumentrevision',
            index=models.Index(fields=['document', 'status'], name='opc_control_documen_81ad55_idx'),
        ),
        migrations.AddIndex(
            model_name='controlleddocumentrevision',
            index=models.Index(fields=['effective_from', 'effective_to'], name='opc_control_effecti_3304e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='controlleddocumentrevision',
            unique_together={('document', 'revision')},
        ),
        migrations.AddIndex(
            model_name='engineeringchangeobjectlink',
            index=models.Index(fields=['object_type', 'object_id'], name='opc_enginee_object__8f2c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='engineeringchangeobjectlink',
            index=models.Index(fields=['role'], name='opc_enginee_role_207d05_idx'),
        ),
        migrations.AddIndex(
            model_name='opcnodedocumentrequirement',
            index=models.Index(fields=['node', 'sequence'], name='opc_opcnode_node_id_e07777_idx'),
        ),
        migrations.AddIndex(
            model_name='opcnodedocumentrequirement',
            index=models.Index(fields=['document_revision'], name='opc_opcnode_documen_d6b355_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='opcnodedocumentrequirement',
            unique_together={('node', 'document_revision', 'purpose')},
        ),
        migrations.AddIndex(
            model_name='opcoperationmaterialallocation',
            index=models.Index(fields=['node', 'sequence'], name='opc_opcoper_node_id_440c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='opcoperationmaterialallocation',
            index=models.Index(fields=['bom_line'], name='opc_opcoper_bom_lin_426014_idx'),
        ),
        migrations.AddIndex(
            model_name='opcoperationmaterialallocation',
            index=models.Index(fields=['component_item_revision'], name='opc_opcoper_compone_500693_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='opcoperationmaterialallocation',
            unique_together={('node', 'bom_line', 'allocation_type')},
        ),
    ]
