# Generated by Django 6.0.6 on 2026-07-29 05:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_items', '0008_remove_sequencedefinition_uniq_sequence_scope_per_version_and_more'),
        ('opc', '0009_manufacturingoperation_productionorder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOT_READY', 'Not ready'), ('READY', 'Ready'), ('DISPATCHED', 'Dispatched'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked'), ('CANCELLED', 'Cancelled')], default='NOT_READY', max_length=20)),
                ('execution_version', models.PositiveBigIntegerField(default=0)),
                ('dispatch_priority', models.PositiveIntegerField(default=100)),
                ('ready', models.BooleanField(default=False)),
                ('block_reason', models.TextField(blank=True)),
                ('planned_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('produced_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('accepted_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('rejected_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('scrapped_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('rework_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('actual_setup_seconds', models.PositiveIntegerField(default=0)),
                ('actual_run_seconds', models.PositiveIntegerField(default=0)),
                ('active_interval', models.CharField(blank=True, max_length=10)),
                ('active_interval_started_at', models.DateTimeField(blank=True, null=True)),
                ('first_started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_cycle_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_executions', to='opc.machineasset')),
                ('assigned_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_operation_executions', to=settings.AUTH_USER_MODEL)),
                ('manufacturing_operation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='execution', to='opc.manufacturingoperation')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_executions', to='opc.productionorder')),
            ],
            options={
                'ordering': ['production_order__order_number', 'manufacturing_operation__sequence'],
            },
        ),
        migrations.CreateModel(
            name='OperationExecutionCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_number', models.PositiveIntegerField(default=1)),
                ('reason', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_operation_execution_cycles', to=settings.AUTH_USER_MODEL)),
                ('operation_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='opc.operationexecution')),
                ('source_rework_edge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execution_cycles', to='opc.manufacturingoperationprecedence')),
            ],
            options={
                'ordering': ['operation_execution', 'cycle_number'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingExecutionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_sequence', models.PositiveBigIntegerField()),
                ('event_type', models.CharField(choices=[('DISPATCH', 'Dispatch'), ('ASSIGN_OPERATOR', 'Assign operator'), ('ASSIGN_MACHINE', 'Assign machine'), ('START', 'Start'), ('PAUSE', 'Pause'), ('RESUME', 'Resume'), ('RECORD_OUTPUT', 'Record output'), ('COMPLETE', 'Complete'), ('BLOCK', 'Block'), ('UNBLOCK', 'Unblock'), ('CANCEL', 'Cancel'), ('CONSUME_MATERIAL', 'Consume material'), ('REVERSE_MATERIAL', 'Reverse material'), ('TOOLING_USAGE', 'Tooling usage'), ('DOCUMENT_ACK', 'Document acknowledgement'), ('REWORK', 'Rework'), ('GENEALOGY_LINK', 'Genealogy link')], max_length=40)),
                ('event_timestamp', models.DateTimeField()),
                ('server_recorded_at', models.DateTimeField(auto_now_add=True)),
                ('produced_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('accepted_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('rejected_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('scrapped_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('rework_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=120)),
                ('previous_execution_version', models.PositiveBigIntegerField()),
                ('new_execution_version', models.PositiveBigIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_execution_events', to=settings.AUTH_USER_MODEL)),
                ('assigned_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_execution_operator_events', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_execution_events', to='opc.machineasset')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_events', to='opc.productionorder')),
                ('operation_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='opc.operationexecution')),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='opc.operationexecutioncycle')),
            ],
            options={
                'ordering': ['operation_execution', 'event_sequence'],
            },
        ),
        migrations.CreateModel(
            name='ProductionDocumentAcknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acknowledged_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_document_acknowledgements', to=settings.AUTH_USER_MODEL)),
                ('controlled_document_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_acknowledgements', to='opc.controlleddocumentrevision')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='document_acknowledgement', to='opc.manufacturingexecutionevent')),
                ('operation_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_acknowledgements', to='opc.operationexecution')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_acknowledgements', to='opc.productionorder')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgements', to='opc.productiondocumentrequirement')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_lots', to=settings.AUTH_USER_MODEL)),
                ('item_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_lots', to='enterprise_items.itemrevision')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='opc.productionorder')),
            ],
            options={
                'ordering': ['lot_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductionSerial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_serials', to=settings.AUTH_USER_MODEL)),
                ('item_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_serials', to='enterprise_items.itemrevision')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='opc.productionlot')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='opc.productionorder')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductionMaterialConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit', models.CharField(max_length=30)),
                ('consumption_type', models.CharField(choices=[('CONSUME', 'Consume'), ('REVERSAL', 'Reversal')], default='CONSUME', max_length=20)),
                ('consumed_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_material_consumptions', to=settings.AUTH_USER_MODEL)),
                ('component_item_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_consumptions', to='enterprise_items.itemrevision')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_consumptions', to='opc.operationexecutioncycle')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='material_consumption', to='opc.manufacturingexecutionevent')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_consumptions', to='opc.productionlot')),
                ('operation_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='opc.operationexecution')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='opc.productionorder')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='opc.productionmaterialrequirement')),
                ('serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_consumptions', to='opc.productionserial')),
            ],
            options={
                'ordering': ['consumed_at'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingGenealogyLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linked_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_genealogy_links', to=settings.AUTH_USER_MODEL)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='genealogy_link', to='opc.manufacturingexecutionevent')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genealogy_links', to='opc.productionorder')),
                ('component_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_genealogy_links', to='opc.productionlot')),
                ('parent_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_genealogy_links', to='opc.productionlot')),
                ('consumption', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genealogy_links', to='opc.productionmaterialconsumption')),
                ('component_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_genealogy_links', to='opc.productionserial')),
                ('parent_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_genealogy_links', to='opc.productionserial')),
            ],
            options={
                'ordering': ['linked_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionToolingUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('used_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_tooling_usages', to=settings.AUTH_USER_MODEL)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tooling_usage', to='opc.manufacturingexecutionevent')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tooling_usages', to='opc.machineasset')),
                ('operation_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooling_usages', to='opc.operationexecution')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooling_usages', to='opc.productionorder')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='opc.productiontoolingrequirement')),
                ('tooling_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_usages', to='opc.toolingdefinition')),
            ],
        ),
        migrations.AddIndex(
            model_name='operationexecution',
            index=models.Index(fields=['production_order', 'status'], name='opc_operati_product_bb8973_idx'),
        ),
        migrations.AddIndex(
            model_name='operationexecution',
            index=models.Index(fields=['ready', 'status'], name='opc_operati_ready_35ec81_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='operationexecutioncycle',
            unique_together={('operation_execution', 'cycle_number')},
        ),
        migrations.AddIndex(
            model_name='manufacturingexecutionevent',
            index=models.Index(fields=['production_order', 'event_type'], name='opc_manufac_product_19a7ad_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturingexecutionevent',
            index=models.Index(fields=['operation_execution', 'event_type'], name='opc_manufac_operati_acfadb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='manufacturingexecutionevent',
            unique_together={('operation_execution', 'event_sequence'), ('operation_execution', 'idempotency_key')},
        ),
        migrations.AlterUniqueTogether(
            name='productiondocumentacknowledgement',
            unique_together={('operation_execution', 'requirement', 'actor')},
        ),
        migrations.AlterUniqueTogether(
            name='productionlot',
            unique_together={('item_revision', 'lot_number')},
        ),
        migrations.AlterUniqueTogether(
            name='productionserial',
            unique_together={('item_revision', 'serial_number')},
        ),
        migrations.AddIndex(
            model_name='productionmaterialconsumption',
            index=models.Index(fields=['production_order', 'requirement'], name='opc_product_product_7a271e_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturinggenealogylink',
            index=models.Index(fields=['production_order'], name='opc_manufac_product_3c5b72_idx'),
        ),
    ]
