# Generated by Django 6.0.6 on 2026-07-29 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opc', '0011_phase9_quality_inspection_ncr'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformancerecord',
            name='quality_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ncr_record', to='opc.qualityevent'),
        ),
    ]
