# Generated by Django 6.0.6 on 2026-07-29 07:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_items', '0008_remove_sequencedefinition_uniq_sequence_scope_per_version_and_more'),
        ('opc', '0012_phase9_ncr_event_idempotency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location_type', models.CharField(choices=[('ZONE', 'Zone'), ('AISLE', 'Aisle'), ('RACK', 'Rack'), ('BIN', 'Bin'), ('FLOOR', 'Floor'), ('STAGING', 'Staging'), ('QUARANTINE', 'Quarantine'), ('SCRAP', 'Scrap')], default='BIN', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('inventory_enabled', models.BooleanField(default=True)),
                ('quarantine', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='opc.storagelocation')),
            ],
            options={
                'ordering': ['warehouse__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_number', models.CharField(max_length=80, unique=True)),
                ('transaction_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('TRANSFER', 'Transfer'), ('RESERVATION', 'Reservation'), ('RESERVATION_RELEASE', 'Reservation release'), ('PRODUCTION_ISSUE', 'Production issue'), ('PRODUCTION_RETURN', 'Production return'), ('CONSUMPTION_RECONCILIATION', 'Consumption reconciliation'), ('ADJUSTMENT_IN', 'Adjustment in'), ('ADJUSTMENT_OUT', 'Adjustment out'), ('QUARANTINE', 'Quarantine'), ('QUALITY_RELEASE', 'Quality release'), ('SCRAP', 'Scrap'), ('REVERSAL', 'Reversal')], max_length=40)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit', models.CharField(max_length=30)),
                ('source_stock_status', models.CharField(blank=True, choices=[('AVAILABLE', 'Available'), ('QUARANTINED', 'Quarantined'), ('BLOCKED', 'Blocked'), ('SCRAP', 'Scrap'), ('IN_TRANSIT', 'In transit')], max_length=30)),
                ('destination_stock_status', models.CharField(blank=True, choices=[('AVAILABLE', 'Available'), ('QUARANTINED', 'Quarantined'), ('BLOCKED', 'Blocked'), ('SCRAP', 'Scrap'), ('IN_TRANSIT', 'In transit')], max_length=30)),
                ('ownership', models.CharField(blank=True, max_length=80)),
                ('event_timestamp', models.DateTimeField()),
                ('server_recorded_at', models.DateTimeField(auto_now_add=True)),
                ('command_scope', models.CharField(max_length=80)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('reason_code', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('destination_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_inventory_transactions', to='opc.productionlot')),
                ('destination_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_inventory_transactions', to='opc.productionserial')),
                ('disposition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='opc.qualitydisposition')),
                ('item_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='enterprise_items.itemrevision')),
                ('material_consumption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='opc.productionmaterialconsumption')),
                ('material_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='opc.productionmaterialrequirement')),
                ('nonconformance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='opc.nonconformancerecord')),
                ('operation_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='opc.operationexecution')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='opc.productionorder')),
                ('quality_hold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='opc.qualityhold')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='opc.inventorytransaction')),
                ('source_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_inventory_transactions', to='opc.productionlot')),
                ('source_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_inventory_transactions', to='opc.productionserial')),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_inventory_transactions', to='opc.storagelocation')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_inventory_transactions', to='opc.storagelocation')),
            ],
            options={
                'ordering': ['-server_recorded_at', '-transaction_number'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINED', 'Quarantined'), ('BLOCKED', 'Blocked'), ('SCRAP', 'Scrap'), ('IN_TRANSIT', 'In transit')], default='AVAILABLE', max_length=30)),
                ('ownership', models.CharField(blank=True, max_length=80)),
                ('unit', models.CharField(default='EA', max_length=30)),
                ('on_hand_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('reserved_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('balance_version', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='enterprise_items.itemrevision')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='opc.productionlot')),
                ('serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='opc.productionserial')),
                ('last_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='opc.inventorytransaction')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='opc.storagelocation')),
            ],
            options={
                'ordering': ['item_revision__item__item_code', 'warehouse__code', 'location__code', 'stock_status'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('warehouse_type', models.CharField(choices=[('GENERAL', 'General'), ('PRODUCTION', 'Production'), ('RECEIVING', 'Receiving'), ('QUARANTINE', 'Quarantine'), ('SCRAP', 'Scrap'), ('TOOLING', 'Tooling'), ('OTHER', 'Other')], default='GENERAL', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='opc.plant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='opc.warehouse'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_inventory_transactions', to='opc.warehouse'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_inventory_transactions', to='opc.warehouse'),
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('released_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('issued_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('unit', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PARTIALLY_ISSUED', 'Partially issued'), ('FULLY_ISSUED', 'Fully issued'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=30)),
                ('reservation_version', models.PositiveBigIntegerField(default=0)),
                ('reserved_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='opc.inventorybalance')),
                ('item_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='enterprise_items.itemrevision')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='opc.productionlot')),
                ('material_requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='opc.productionmaterialrequirement')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='opc.productionorder')),
                ('reserved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to=settings.AUTH_USER_MODEL)),
                ('serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='opc.productionserial')),
                ('last_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='opc.inventorytransaction')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='opc.storagelocation')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='opc.warehouse')),
            ],
            options={
                'ordering': ['production_order__order_number', 'material_requirement__sequence', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='opc.warehouse'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['active', 'warehouse_type'], name='opc_warehou_active_d28d10_idx'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['warehouse', 'active', 'inventory_enabled'], name='opc_storage_warehou_a419dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storagelocation',
            unique_together={('warehouse', 'code')},
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_type', 'server_recorded_at'], name='opc_invento_transac_ee8992_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['production_order', 'transaction_type'], name='opc_invento_product_fb6dae_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['material_requirement', 'transaction_type'], name='opc_invento_materia_fa1be0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['source_warehouse', 'source_location'], name='opc_invento_source__586e43_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['destination_warehouse', 'destination_location'], name='opc_invento_destina_69ea89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorytransaction',
            unique_together={('command_scope', 'idempotency_key')},
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['production_order', 'status'], name='opc_invento_product_a0cc56_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['material_requirement', 'status'], name='opc_invento_materia_78c8dc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['balance', 'status'], name='opc_invento_balance_fa1c40_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['item_revision', 'stock_status'], name='opc_invento_item_re_6c4efa_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['warehouse', 'location', 'stock_status'], name='opc_invento_warehou_8c5e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['serial', 'stock_status'], name='opc_invento_serial__f86b90_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorybalance',
            unique_together={('item_revision', 'warehouse', 'location', 'lot', 'serial', 'stock_status', 'ownership')},
        ),
    ]
