# Generated by Django 6.0.6 on 2026-07-29 10:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_items', '0008_remove_sequencedefinition_uniq_sequence_scope_per_version_and_more'),
        ('opc', '0015_phase12_capacity_finite_scheduling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FailureCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RemedyCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MaintainableAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('AREA', 'Area'), ('SYSTEM', 'System'), ('SUBASSEMBLY', 'Subassembly'), ('TOOLING', 'Tooling'), ('FACILITY', 'Facility'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('location_code', models.CharField(blank=True, max_length=80)),
                ('classification', models.CharField(blank=True, max_length=120)),
                ('criticality', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('operational_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RUNNING', 'Running'), ('IDLE', 'Idle'), ('PLANNED_DOWN', 'Planned down'), ('BREAKDOWN', 'Breakdown'), ('MAINTENANCE', 'Maintenance'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='opc.maintainableasset')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintainable_assets', to='opc.plant')),
                ('work_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintainable_assets', to='opc.workcenter')),
            ],
            options={
                'ordering': ['asset_code'],
            },
        ),
        migrations.CreateModel(
            name='MachineMaintenanceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classification', models.CharField(blank=True, max_length=120)),
                ('criticality', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('operational_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RUNNING', 'Running'), ('IDLE', 'Idle'), ('PLANNED_DOWN', 'Planned down'), ('BREAKDOWN', 'Breakdown'), ('MAINTENANCE', 'Maintenance'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=30)),
                ('maintenance_location', models.CharField(blank=True, max_length=120)),
                ('risk_notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('profile_version', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_profile', to='opc.machineasset')),
                ('parent_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_profiles', to='opc.maintainableasset')),
            ],
            options={
                'ordering': ['machine__asset_code'],
            },
        ),
        migrations.CreateModel(
            name='AssetMeter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('meter_type', models.CharField(choices=[('RUNTIME_HOURS', 'Runtime hours'), ('CYCLES', 'Cycles'), ('DISTANCE', 'Distance'), ('ENERGY', 'Energy'), ('CUSTOM', 'Custom')], default='RUNTIME_HOURS', max_length=30)),
                ('unit', models.CharField(default='H', max_length=30)),
                ('rollover_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='opc.machineasset')),
                ('maintainable_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='opc.maintainableasset')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('TRIAGED', 'Triaged'), ('CONVERTED', 'Converted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('request_version', models.PositiveBigIntegerField(default=0)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('failure_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='opc.failurecode')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='opc.machineasset')),
                ('maintainable_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='opc.maintainableasset')),
                ('operation_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='opc.operationexecution')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='opc.productionorder')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', 'request_number'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('estimated_duration_hours', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('safety_notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_task_templates', to='opc.laborskill')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTaskChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(max_length=255)),
                ('mandatory', models.BooleanField(default=True)),
                ('expected_result', models.CharField(blank=True, max_length=255)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='opc.maintenancetasktemplate')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_order_number', models.CharField(max_length=80, unique=True)),
                ('work_order_type', models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('CORRECTIVE', 'Corrective'), ('BREAKDOWN', 'Breakdown'), ('INSPECTION', 'Inspection')], default='CORRECTIVE', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PLANNED', 'Planned'), ('RELEASED', 'Released'), ('IN_PROGRESS', 'In progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration_hours', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('downtime_required', models.BooleanField(default=True)),
                ('work_order_version', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_maintenance_work_orders', to=settings.AUTH_USER_MODEL)),
                ('cause_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='opc.causecode')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_maintenance_work_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_maintenance_work_orders', to=settings.AUTH_USER_MODEL)),
                ('downtime_exception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_work_orders', to='opc.calendarexception')),
                ('failure_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='opc.failurecode')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_work_orders', to='opc.machineasset')),
                ('maintainable_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_work_orders', to='opc.maintainableasset')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='opc.maintenancerequest')),
                ('task_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='opc.maintenancetasktemplate')),
            ],
            options={
                'ordering': ['-created_at', 'work_order_number'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSparePartRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit', models.CharField(default='EA', max_length=30)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('RESERVED', 'Reserved'), ('ISSUED', 'Issued'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('issued_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('returned_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('requirement_version', models.PositiveBigIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('item_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_spare_requirements', to='enterprise_items.itemrevision')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_part_requirements', to='opc.maintenanceworkorder')),
            ],
            options={
                'ordering': ['work_order__work_order_number', 'item_revision__item__item_code'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSparePartIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('returned_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issue_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_spare_issues', to='opc.inventorytransaction')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_spare_part_issues', to=settings.AUTH_USER_MODEL)),
                ('return_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_spare_returns', to='opc.inventorytransaction')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='opc.maintenancesparepartrequirement')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spare_part_issues', to='opc.maintenanceworkorder')),
            ],
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='converted_work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='opc.maintenanceworkorder'),
        ),
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('PLANNED', 'Planned'), ('RELEASED', 'Released'), ('STARTED', 'Started'), ('PAUSED', 'Paused'), ('RESUMED', 'Resumed'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('CHECKLIST', 'Checklist'), ('PART_ISSUED', 'Part_Issued'), ('PART_RETURNED', 'Part_Returned'), ('METER_READING', 'Meter_Reading')], max_length=30)),
                ('event_timestamp', models.DateTimeField()),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('idempotency_key', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_events', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='opc.maintenanceworkorder')),
            ],
            options={
                'ordering': ['event_timestamp', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceChecklistResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(max_length=255)),
                ('mandatory', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PASS', 'Pass'), ('FAIL', 'Fail'), ('NA', 'N/A')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_checklist_results', to=settings.AUTH_USER_MODEL)),
                ('template_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='opc.maintenancetaskchecklistitem')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_results', to='opc.maintenanceworkorder')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MachineDowntimeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('downtime_type', models.CharField(choices=[('PLANNED', 'Planned'), ('UNPLANNED', 'Unplanned'), ('BREAKDOWN', 'Breakdown')], max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('planned', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calendar_exception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='downtime_events', to='opc.calendarexception')),
                ('cause_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='downtime_events', to='opc.causecode')),
                ('failure_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='downtime_events', to='opc.failurecode')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downtime_events', to='opc.machineasset')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='downtime_events', to='opc.maintenanceworkorder')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWorkOrderSkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_hours', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('required_count', models.PositiveIntegerField(default=1)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_work_order_requirements', to='opc.laborskill')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='opc.maintenanceworkorder')),
            ],
        ),
        migrations.CreateModel(
            name='PreventiveMaintenancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_number', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('trigger_type', models.CharField(choices=[('CALENDAR', 'Calendar'), ('METER', 'Meter'), ('THRESHOLD', 'Threshold')], default='CALENDAR', max_length=30)),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('meter_interval', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('next_due_meter_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('generate_horizon_days', models.PositiveIntegerField(default=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('plan_version', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_pm_plans', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pm_plans', to='opc.machineasset')),
                ('maintainable_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pm_plans', to='opc.maintainableasset')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pm_plans', to='opc.assetmeter')),
                ('task_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pm_plans', to='opc.maintenancetasktemplate')),
            ],
            options={
                'ordering': ['plan_number'],
            },
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='preventive_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='opc.preventivemaintenanceplan'),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='remedy_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='opc.remedycode'),
        ),
        migrations.CreateModel(
            name='AssetMeterReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reading_value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('reading_timestamp', models.DateTimeField()),
                ('source', models.CharField(default='MANUAL', max_length=80)),
                ('idempotency_key', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='opc.assetmeter')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_meter_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reading_timestamp', '-created_at'],
                'indexes': [models.Index(fields=['meter', 'reading_timestamp'], name='opc_assetme_meter_i_490afc_idx')],
                'unique_together': {('meter', 'idempotency_key')},
            },
        ),
        migrations.AddIndex(
            model_name='maintainableasset',
            index=models.Index(fields=['plant', 'work_center', 'active'], name='opc_maintai_plant_i_cd802d_idx'),
        ),
        migrations.AddIndex(
            model_name='maintainableasset',
            index=models.Index(fields=['parent', 'active'], name='opc_maintai_parent__ddcdf9_idx'),
        ),
        migrations.AddIndex(
            model_name='machinemaintenanceprofile',
            index=models.Index(fields=['criticality', 'operational_status'], name='opc_machine_critica_dc9b81_idx'),
        ),
        migrations.AddIndex(
            model_name='machinemaintenanceprofile',
            index=models.Index(fields=['active'], name='opc_machine_active_ddfb0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetmeter',
            unique_together={('machine', 'code'), ('maintainable_asset', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='maintenancetaskchecklistitem',
            unique_together={('template', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='maintenanceevent',
            unique_together={('work_order', 'event_type', 'idempotency_key')},
        ),
        migrations.AlterUniqueTogether(
            name='maintenancechecklistresult',
            unique_together={('work_order', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='machinedowntimeevent',
            index=models.Index(fields=['machine', 'start_datetime', 'end_datetime'], name='opc_machine_machine_334328_idx'),
        ),
        migrations.AddIndex(
            model_name='machinedowntimeevent',
            index=models.Index(fields=['planned', 'downtime_type'], name='opc_machine_planned_d622b9_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenanceplan',
            index=models.Index(fields=['status', 'next_due_date'], name='opc_prevent_status_38696c_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenanceplan',
            index=models.Index(fields=['machine', 'status'], name='opc_prevent_machine_41e14e_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceworkorder',
            index=models.Index(fields=['status', 'priority'], name='opc_mainten_status_0804d8_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceworkorder',
            index=models.Index(fields=['machine', 'status'], name='opc_mainten_machine_ba16d8_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceworkorder',
            index=models.Index(fields=['planned_start', 'planned_end'], name='opc_mainten_planned_536072_idx'),
        ),
    ]
