[pytest]
DJANGO_SETTINGS_MODULE = KTCProject.settings
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    --reuse-db
    -v
    --tb=short
markers =
    slow: تست‌هایی که زمان بیشتری می‌گیرند
    integration: تست‌های یکپارچه‌سازی
