# Generated by Django 6.0.5 on 2026-07-05 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='enterprise_items.codingorganization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='enterprise_items.itemcategory')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('organization', 'parent', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20)),
                ('group', models.CharField(choices=[('MATERIAL', 'Material'), ('PART', 'Part'), ('WIP', 'Work in process'), ('ASSEMBLY', 'Assembly'), ('TOOLING', 'Tooling'), ('ASSET', 'Asset'), ('CONSUMABLE', 'Consumable'), ('SERVICE', 'Service')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_types', to='enterprise_items.codingorganization')),
            ],
            options={
                'ordering': ['group', 'code'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(db_index=True, max_length=160)),
                ('name', models.CharField(max_length=255)),
                ('base_unit', models.CharField(default='EA', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('OBSOLETE', 'Obsolete'), ('BLOCKED', 'Blocked')], default='DRAFT', max_length=16)),
                ('tracking_mode', models.CharField(choices=[('NONE', 'None'), ('LOT', 'Lot'), ('SERIAL', 'Serial'), ('LOT_SERIAL', 'Lot and serial')], default='NONE', max_length=16)),
                ('drawing_no', models.CharField(blank=True, max_length=120)),
                ('specification', models.TextField(blank=True)),
                ('default_revision', models.CharField(default='R0', max_length=30)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enterprise_items', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='enterprise_items.codingorganization')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='enterprise_items.itemcategory')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='enterprise_items.itemtype')),
            ],
            options={
                'ordering': ['item_code'],
            },
        ),
        migrations.CreateModel(
            name='CodeScheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('prefix', models.CharField(max_length=30)),
                ('separator', models.CharField(default='-', max_length=4)),
                ('sequence_padding', models.PositiveSmallIntegerField(default=5)),
                ('next_sequence', models.PositiveIntegerField(default=1)),
                ('include_category', models.BooleanField(default=True)),
                ('include_revision', models.BooleanField(default=False)),
                ('include_stage', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_schemes', to='enterprise_items.codingorganization')),
                ('item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_schemes', to='enterprise_items.itemtype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant_code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_variants', to='enterprise_items.item')),
                ('opc_diagram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturing_variants', to='opc.opcdiagram')),
            ],
            options={
                'ordering': ['item__item_code', 'variant_code'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStageCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_code', models.CharField(max_length=40)),
                ('stage_name', models.CharField(max_length=180)),
                ('output_item_code', models.CharField(max_length=180)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('creates_inventory_identity', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_codes', to='enterprise_items.manufacturingvariant')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='VariantInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('CASTING', 'Casting'), ('SHEET', 'Sheet'), ('BAR', 'Bar'), ('PIPE', 'Pipe'), ('FORGING', 'Forging'), ('BILLET', 'Billet'), ('PURCHASED_SEMI_FINISHED', 'Purchased semi-finished'), ('EXISTING_ITEM', 'Existing item'), ('FREE_SPEC', 'Free specification')], max_length=32)),
                ('material_grade', models.CharField(blank=True, max_length=120)),
                ('shape', models.CharField(blank=True, max_length=120)),
                ('dimensions', models.CharField(blank=True, max_length=180)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=14)),
                ('unit', models.CharField(default='EA', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('linked_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_as_variant_input', to='enterprise_items.item')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='enterprise_items.manufacturingvariant')),
            ],
            options={
                'ordering': ['source_type', 'material_grade'],
            },
        ),
        migrations.CreateModel(
            name='ItemRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.CharField(max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('drawing_no', models.CharField(blank=True, max_length=120)),
                ('specification', models.TextField(blank=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='enterprise_items.item')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('item', 'revision')},
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['organization', 'status'], name='enterprise__organiz_fdb6fb_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_code'], name='enterprise__item_co_0947e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('organization', 'item_code')},
        ),
        migrations.AlterUniqueTogether(
            name='codescheme',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='manufacturingvariant',
            unique_together={('item', 'variant_code')},
        ),
        migrations.AlterUniqueTogether(
            name='processstagecode',
            unique_together={('variant', 'output_item_code'), ('variant', 'stage_code')},
        ),
    ]
