# Generated by Django 6.0.5 on 2026-07-18 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='make_or_buy',
            field=models.CharField(choices=[('MAKE', 'Make'), ('BUY', 'Buy'), ('MAKE_OR_BUY', 'Make or buy'), ('OUTSOURCE', 'Outsource'), ('PHANTOM', 'Phantom')], default='MAKE', max_length=16),
        ),
        migrations.AddField(
            model_name='itemrevision',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemrevision',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_item_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemrevision',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itemrevision',
            name='dimensions',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='itemrevision',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemrevision',
            name='material_specification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itemrevision',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemrevision',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_item_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemrevision',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('RELEASED', 'Released'), ('SUPERSEDED', 'Superseded'), ('OBSOLETE', 'Obsolete')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='itemrevision',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemrevision',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_item_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemrevision',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemrevision',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='enterprise_items.itemrevision'),
        ),
        migrations.AddField(
            model_name='itemrevision',
            name='technical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itemrevision',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemrevision',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='itemrevision',
            name='weight_unit',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='item',
            name='tracking_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('LOT', 'Lot / batch'), ('BATCH', 'Batch'), ('SERIAL', 'Serial'), ('LOT_SERIAL', 'Lot and serial'), ('BATCH_AND_SERIAL', 'Batch and serial')], default='NONE', max_length=16),
        ),
        migrations.AlterField(
            model_name='itemrevision',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='enterprise_items.item'),
        ),
        migrations.AddIndex(
            model_name='itemrevision',
            index=models.Index(fields=['item', 'status'], name='enterprise__item_id_3a2fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='itemrevision',
            index=models.Index(fields=['effective_from', 'effective_to'], name='enterprise__effecti_ad8510_idx'),
        ),
    ]
