# Generated by Django 6.0.6 on 2026-07-18 06:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_items', '0002_item_is_active_item_make_or_buy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bom_code', models.CharField(blank=True, max_length=80)),
                ('bom_type', models.CharField(choices=[('ENGINEERING', 'Engineering'), ('MANUFACTURING', 'Manufacturing'), ('SERVICE', 'Service'), ('PHANTOM', 'Phantom')], default='ENGINEERING', max_length=24)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boms', to=settings.AUTH_USER_MODEL)),
                ('parent_item_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='enterprise_items.itemrevision')),
            ],
            options={
                'ordering': ['parent_item_revision__item__item_code', 'bom_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BOMRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('RELEASED', 'Released'), ('SUPERSEDED', 'Superseded'), ('OBSOLETE', 'Obsolete')], default='DRAFT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bom_revisions', to=settings.AUTH_USER_MODEL)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='enterprise_items.bom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bom_revisions', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_bom_revisions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_bom_revisions', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='enterprise_items.bomrevision')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit', models.CharField(default='EA', max_length=30)),
                ('scrap_percent', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('is_phantom', models.BooleanField(default=False)),
                ('is_optional', models.BooleanField(default=False)),
                ('reference_designator', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_item_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_bom_lines', to='enterprise_items.itemrevision')),
                ('bom_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='enterprise_items.bomrevision')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['parent_item_revision', 'bom_type'], name='enterprise__parent__4a7863_idx'),
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['is_active'], name='enterprise__is_acti_63eeb2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together={('parent_item_revision', 'bom_type', 'bom_code')},
        ),
        migrations.AddIndex(
            model_name='bomrevision',
            index=models.Index(fields=['bom', 'status'], name='enterprise__bom_id_7a4673_idx'),
        ),
        migrations.AddIndex(
            model_name='bomrevision',
            index=models.Index(fields=['effective_from', 'effective_to'], name='enterprise__effecti_40b42a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bomrevision',
            unique_together={('bom', 'revision')},
        ),
        migrations.AddIndex(
            model_name='bomline',
            index=models.Index(fields=['bom_revision', 'component_item_revision'], name='enterprise__bom_rev_a8bc75_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bomline',
            unique_together={('bom_revision', 'sequence')},
        ),
    ]
