# Generated by Django 6.0.5 on 2026-07-18 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_items', '0003_bom_bomrevision_bomline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCodingTemplateSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('segment_type', models.CharField(choices=[('LITERAL', 'Literal'), ('CLASSIFICATION_CODE', 'Classification code'), ('ATTRIBUTE', 'Attribute'), ('SEQUENCE', 'Sequence'), ('CHECK_DIGIT', 'Check digit')], max_length=32)),
                ('literal_value', models.CharField(blank=True, max_length=80)),
                ('classification_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('required', models.BooleanField(default=True)),
                ('fallback_value', models.CharField(blank=True, max_length=80)),
                ('prefix', models.CharField(blank=True, max_length=20)),
                ('suffix', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ItemIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier_type', models.CharField(choices=[('LEGACY_CODE', 'Legacy code'), ('MANUFACTURER_PART_NUMBER', 'Manufacturer part number'), ('SUPPLIER_PART_NUMBER', 'Supplier part number'), ('CUSTOMER_PART_NUMBER', 'Customer part number'), ('DRAWING_NUMBER', 'Drawing number'), ('BARCODE', 'Barcode')], max_length=40)),
                ('value', models.CharField(max_length=180)),
                ('normalized_value', models.CharField(db_index=True, max_length=180)),
                ('organization_name', models.CharField(blank=True, max_length=180)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['identifier_type', 'normalized_value'],
            },
        ),
        migrations.CreateModel(
            name='ItemRevisionAttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_text', models.TextField(blank=True)),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('value_integer', models.BigIntegerField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_choice', models.CharField(blank=True, max_length=120)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['attribute_definition__sort_order', 'attribute_definition__code'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='block_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='code_generation_strategy',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='item',
            name='generated_code_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='phase_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='replaced_by_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces_items', to='enterprise_items.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='semantic_identity_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='item',
            name='semantic_identity_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='item',
            name='status_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('OBSOLETE', 'Obsolete'), ('BLOCKED', 'Blocked'), ('PHASE_OUT', 'Phase out'), ('MERGED', 'Merged')], default='DRAFT', max_length=16),
        ),
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('TEXT', 'Text'), ('DECIMAL', 'Decimal'), ('INTEGER', 'Integer'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('CHOICE', 'Choice')], max_length=20)),
                ('unit_dimension', models.CharField(blank=True, max_length=40)),
                ('default_unit', models.CharField(blank=True, max_length=30)),
                ('is_required', models.BooleanField(default=False)),
                ('is_searchable', models.BooleanField(default=True)),
                ('is_identity_defining', models.BooleanField(default=False)),
                ('is_code_bearing', models.BooleanField(default=False)),
                ('is_duplicate_key', models.BooleanField(default=False)),
                ('is_revision_controlled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('validation_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attribute_definitions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_definitions', to='enterprise_items.codingorganization')),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AttributeEncodingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=180)),
                ('encoding_type', models.CharField(choices=[('LOOKUP', 'Lookup'), ('NUMERIC', 'Numeric'), ('NORMALIZED_TEXT', 'Normalized text'), ('BOOLEAN_TOKEN', 'Boolean token'), ('DATE_PATTERN', 'Date pattern'), ('REFERENCE_CODE', 'Reference code')], max_length=24)),
                ('canonical_unit', models.CharField(blank=True, max_length=30)),
                ('multiplier', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('precision', models.PositiveSmallIntegerField(default=0)),
                ('rounding_policy', models.CharField(choices=[('REJECT', 'Reject non-exact'), ('HALF_UP', 'Half up'), ('DOWN', 'Down')], default='REJECT', max_length=16)),
                ('zero_pad_width', models.PositiveSmallIntegerField(default=0)),
                ('text_case', models.CharField(choices=[('UPPER', 'Uppercase'), ('LOWER', 'Lowercase'), ('PRESERVE', 'Preserve')], default='UPPER', max_length=12)),
                ('max_length', models.PositiveSmallIntegerField(default=30)),
                ('true_token', models.CharField(default='Y', max_length=20)),
                ('false_token', models.CharField(default='N', max_length=20)),
                ('date_pattern', models.CharField(blank=True, max_length=20)),
                ('prefix', models.CharField(blank=True, max_length=20)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attribute_encoding_rules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_encoding_rules', to='enterprise_items.codingorganization')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AttributeEncodingOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_value', models.CharField(max_length=180)),
                ('encoded_value', models.CharField(max_length=60)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='enterprise_items.attributeencodingrule')),
            ],
            options={
                'ordering': ['sort_order', 'source_value'],
            },
        ),
        migrations.CreateModel(
            name='ItemClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, db_index=True, max_length=700)),
                ('coding_prefix', models.CharField(blank=True, max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_item_classifications', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_classifications', to='enterprise_items.codingorganization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='enterprise_items.itemclassification')),
            ],
            options={
                'ordering': ['path', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_override', models.BooleanField(blank=True, null=True)),
                ('code_bearing_override', models.BooleanField(blank=True, null=True)),
                ('identity_defining_override', models.BooleanField(blank=True, null=True)),
                ('duplicate_key_override', models.BooleanField(blank=True, null=True)),
                ('default_unit', models.CharField(blank=True, max_length=30)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('inherited', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classification_assignments', to='enterprise_items.attributedefinition')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classification_attributes', to=settings.AUTH_USER_MODEL)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_assignments', to='enterprise_items.itemclassification')),
            ],
            options={
                'ordering': ['display_order', 'attribute_definition__code'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='enterprise_items.itemclassification'),
        ),
        migrations.CreateModel(
            name='ItemCodingScheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=180)),
                ('strategy', models.CharField(choices=[('SEMANTIC', 'Semantic'), ('HYBRID', 'Hybrid'), ('SEQUENTIAL', 'Sequential'), ('MANUAL_CONTROLLED', 'Manual controlled'), ('LEGACY', 'Legacy')], max_length=24)),
                ('separator', models.CharField(default='-', max_length=4)),
                ('maximum_length', models.PositiveSmallIntegerField(default=80)),
                ('case_policy', models.CharField(choices=[('UPPER', 'Uppercase'), ('LOWER', 'Lowercase'), ('PRESERVE', 'Preserve')], default='UPPER', max_length=12)),
                ('sequence_scope', models.CharField(choices=[('GLOBAL', 'Global'), ('COMPANY', 'Company'), ('DOMAIN', 'Domain'), ('CLASSIFICATION', 'Classification')], default='GLOBAL', max_length=24)),
                ('sequence_length', models.PositiveSmallIntegerField(default=6)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_item_coding_schemes', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_coding_schemes', to='enterprise_items.codingorganization')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ItemCodeSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_key', models.CharField(max_length=180)),
                ('next_sequence', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coding_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='enterprise_items.itemcodingscheme')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='coding_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='enterprise_items.itemcodingscheme'),
        ),
        migrations.CreateModel(
            name='ItemCodingTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('fallback_sequence_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_item_coding_templates', to=settings.AUTH_USER_MODEL)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coding_templates', to='enterprise_items.itemclassification')),
                ('coding_scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='enterprise_items.itemcodingscheme')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_item_coding_templates', to=settings.AUTH_USER_MODEL)),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retired_item_coding_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['classification__path', '-version'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='coding_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='enterprise_items.itemcodingtemplate'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['organization', 'semantic_identity_hash'], name='enterprise__organiz_4402c0_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['organization', 'classification'], name='enterprise__organiz_dd5402_idx'),
        ),
        migrations.AddField(
            model_name='itemcodingtemplatesegment',
            name='attribute_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coding_segments', to='enterprise_items.attributedefinition'),
        ),
        migrations.AddField(
            model_name='itemcodingtemplatesegment',
            name='encoding_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coding_segments', to='enterprise_items.attributeencodingrule'),
        ),
        migrations.AddField(
            model_name='itemcodingtemplatesegment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='enterprise_items.itemcodingtemplate'),
        ),
        migrations.AddField(
            model_name='itemidentifier',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_item_identifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemidentifier',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='enterprise_items.item'),
        ),
        migrations.AddField(
            model_name='itemrevisionattributevalue',
            name='attribute_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revision_values', to='enterprise_items.attributedefinition'),
        ),
        migrations.AddField(
            model_name='itemrevisionattributevalue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_item_revision_attribute_values', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemrevisionattributevalue',
            name='item_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='enterprise_items.itemrevision'),
        ),
        migrations.AddIndex(
            model_name='attributedefinition',
            index=models.Index(fields=['organization', 'is_active'], name='enterprise__organiz_73a31f_idx'),
        ),
        migrations.AddIndex(
            model_name='attributedefinition',
            index=models.Index(fields=['organization', 'data_type'], name='enterprise__organiz_2b69c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attributedefinition',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='attributeencodingrule',
            index=models.Index(fields=['organization', 'encoding_type'], name='enterprise__organiz_6064f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attributeencodingrule',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='attributeencodingoption',
            unique_together={('rule', 'source_value')},
        ),
        migrations.AddIndex(
            model_name='itemclassification',
            index=models.Index(fields=['organization', 'parent'], name='enterprise__organiz_137628_idx'),
        ),
        migrations.AddIndex(
            model_name='itemclassification',
            index=models.Index(fields=['organization', 'is_active'], name='enterprise__organiz_c19420_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemclassification',
            unique_together={('organization', 'parent', 'code')},
        ),
        migrations.AddIndex(
            model_name='classificationattribute',
            index=models.Index(fields=['classification', 'is_active'], name='enterprise__classif_6d9e6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classificationattribute',
            unique_together={('classification', 'attribute_definition')},
        ),
        migrations.AddIndex(
            model_name='itemcodingscheme',
            index=models.Index(fields=['organization', 'strategy'], name='enterprise__organiz_d4230b_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcodingscheme',
            index=models.Index(fields=['organization', 'is_default'], name='enterprise__organiz_8a4440_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcodingscheme',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='itemcodesequence',
            index=models.Index(fields=['coding_scheme', 'scope_key'], name='enterprise__coding__4b36cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcodesequence',
            unique_together={('coding_scheme', 'scope_key')},
        ),
        migrations.AddIndex(
            model_name='itemcodingtemplate',
            index=models.Index(fields=['classification', 'status'], name='enterprise__classif_46788b_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcodingtemplate',
            index=models.Index(fields=['effective_from', 'effective_to'], name='enterprise__effecti_99c6c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcodingtemplate',
            unique_together={('coding_scheme', 'classification', 'version')},
        ),
        migrations.AddIndex(
            model_name='itemcodingtemplatesegment',
            index=models.Index(fields=['template', 'segment_type'], name='enterprise__templat_cacbd5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcodingtemplatesegment',
            unique_together={('template', 'position')},
        ),
        migrations.AddIndex(
            model_name='itemidentifier',
            index=models.Index(fields=['identifier_type', 'normalized_value'], name='enterprise__identif_62b2a2_idx'),
        ),
        migrations.AddIndex(
            model_name='itemidentifier',
            index=models.Index(fields=['item', 'is_primary'], name='enterprise__item_id_8a6590_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemidentifier',
            unique_together={('item', 'identifier_type', 'normalized_value', 'organization_name')},
        ),
        migrations.AddIndex(
            model_name='itemrevisionattributevalue',
            index=models.Index(fields=['item_revision', 'attribute_definition'], name='enterprise__item_re_504051_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemrevisionattributevalue',
            unique_together={('item_revision', 'attribute_definition')},
        ),
    ]
