# Generated by Django 6.0.5 on 2026-07-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_items', '0004_itemcodingtemplatesegment_itemidentifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemidentifier',
            name='normalized_value',
            field=models.CharField(blank=True, db_index=True, default='', max_length=180),
        ),
    ]
