# Generated by Django 6.0.6 on 2026-07-20 09:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_items', '0005_alter_itemidentifier_normalized_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField(default=10)),
                ('display_group', models.CharField(blank=True, default='Primary Characteristics', max_length=80)),
                ('requiredness', models.CharField(choices=[('REQUIRED', 'Required'), ('OPTIONAL', 'Optional'), ('CONDITIONAL', 'Conditional')], default='OPTIONAL', max_length=16)),
                ('identity_defining', models.BooleanField(default=False)),
                ('default_value', models.JSONField(blank=True, default=dict)),
                ('visibility_condition', models.JSONField(blank=True, default=dict)),
                ('required_condition', models.JSONField(blank=True, default=dict)),
                ('display_label_override', models.CharField(blank=True, default='', max_length=180)),
                ('help_text_override', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['structure', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalDataTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['organization', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('TEXT', 'Text'), ('LONG_TEXT', 'Long text'), ('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('SINGLE_SELECT', 'Single select'), ('MULTI_SELECT', 'Multi select'), ('UNIT_VALUE', 'Unit value'), ('RANGE', 'Range'), ('REFERENCE', 'Reference'), ('DOCUMENT_REFERENCE', 'Document reference')], max_length=32)),
                ('display_group', models.CharField(blank=True, default='General', max_length=80)),
                ('scope', models.CharField(choices=[('PART', 'Part'), ('REVISION', 'Revision')], default='REVISION', max_length=16)),
                ('requiredness', models.CharField(choices=[('REQUIRED', 'Required'), ('RECOMMENDED', 'Recommended'), ('OPTIONAL', 'Optional'), ('CONDITIONAL', 'Conditional')], default='OPTIONAL', max_length=16)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('default_value', models.JSONField(blank=True, default=dict)),
                ('validation_config', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['template', 'display_group', 'sort_order'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='coding_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CodeDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('separator', models.CharField(blank=True, default='-', max_length=8)),
                ('maximum_length', models.PositiveIntegerField(default=80)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=16)),
                ('active_version', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_code_definitions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineering_code_definitions', to='enterprise_items.codingorganization')),
            ],
            options={
                'ordering': ['organization', 'code'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='code_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='enterprise_items.codedefinition'),
        ),
        migrations.CreateModel(
            name='CodeDefinitionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=16)),
                ('configuration_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_code_definition_versions', to=settings.AUTH_USER_MODEL)),
                ('code_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='enterprise_items.codedefinition')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_code_definition_versions', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_code_definition_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code_definition', '-version_number'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='code_definition_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='enterprise_items.codedefinitionversion'),
        ),
        migrations.CreateModel(
            name='ParameterDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('TEXT', 'Text'), ('LONG_TEXT', 'Long text'), ('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('SINGLE_SELECT', 'Single select'), ('MULTI_SELECT', 'Multi select'), ('UNIT_VALUE', 'Unit value'), ('RANGE', 'Range'), ('REFERENCE', 'Reference')], max_length=24)),
                ('default_unit', models.CharField(blank=True, default='', max_length=32)),
                ('searchable', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parameter_definitions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineering_parameters', to='enterprise_items.codingorganization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_parameter_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organization', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CodeSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segment_type', models.CharField(choices=[('FIXED_TEXT', 'Fixed text'), ('PARAMETER', 'Parameter'), ('SEQUENCE', 'Sequence'), ('DATE', 'Date'), ('SEPARATOR', 'Separator')], max_length=24)),
                ('sort_order', models.PositiveIntegerField(default=10)),
                ('fixed_value', models.CharField(blank=True, default='', max_length=80)),
                ('requiredness', models.CharField(choices=[('REQUIRED', 'Required'), ('OPTIONAL', 'Optional'), ('CONDITIONAL', 'Conditional')], default='REQUIRED', max_length=16)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('padding', models.CharField(blank=True, default='', max_length=16)),
                ('prefix', models.CharField(blank=True, default='', max_length=32)),
                ('suffix', models.CharField(blank=True, default='', max_length=32)),
                ('transform', models.JSONField(blank=True, default=dict)),
                ('fallback', models.JSONField(blank=True, default=dict)),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='enterprise_items.codedefinitionversion')),
                ('parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='code_segments', to='enterprise_items.parameterdefinition')),
            ],
            options={
                'ordering': ['version', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ParameterMetadataField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('TEXT', 'Text'), ('LONG_TEXT', 'Long text'), ('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('SINGLE_SELECT', 'Single select'), ('MULTI_SELECT', 'Multi select'), ('UNIT_VALUE', 'Unit value'), ('RANGE', 'Range'), ('REFERENCE', 'Reference')], max_length=24)),
                ('group', models.CharField(blank=True, default='General', max_length=80)),
                ('requiredness', models.CharField(choices=[('REQUIRED', 'Required'), ('RECOMMENDED', 'Recommended'), ('OPTIONAL', 'Optional')], default='OPTIONAL', max_length=16)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('default_value', models.JSONField(blank=True, default=dict)),
                ('validation_config', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=10)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_metadata_fields', to='enterprise_items.codingorganization')),
            ],
            options={
                'ordering': ['organization', 'group', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ParameterMetadataValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='enterprise_items.parametermetadatafield')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_values', to='enterprise_items.parameterdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_label', models.CharField(max_length=180)),
                ('stored_value', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=10)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='enterprise_items.parameterdefinition')),
            ],
            options={
                'ordering': ['parameter', 'sort_order', 'display_label'],
            },
        ),
        migrations.CreateModel(
            name='CodeOptionEncoding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encoded_token', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('code_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_encodings', to='enterprise_items.codesegment')),
                ('parameter_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='code_encodings', to='enterprise_items.parameteroption')),
            ],
            options={
                'ordering': ['code_segment', 'encoded_token'],
            },
        ),
        migrations.CreateModel(
            name='PartParameterValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('normalized_value', models.CharField(blank=True, default='', max_length=255)),
                ('display_value', models.CharField(blank=True, default='', max_length=255)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_values', to='enterprise_items.parameterdefinition')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='enterprise_items.item')),
            ],
        ),
        migrations.CreateModel(
            name='PartTechnicalValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_values', to='enterprise_items.item')),
            ],
        ),
        migrations.CreateModel(
            name='RevisionTechnicalValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_values', to='enterprise_items.itemrevision')),
            ],
        ),
        migrations.CreateModel(
            name='SequenceDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('CODE_DEFINITION', 'Code definition'), ('STRUCTURE', 'Structure'), ('PREFIX', 'Prefix'), ('CALENDAR_YEAR', 'Calendar year')], max_length=24)),
                ('starting_value', models.PositiveIntegerField(default=1)),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=5)),
                ('padding_character', models.CharField(default='0', max_length=1)),
                ('reset_policy', models.CharField(blank=True, default='NEVER', max_length=32)),
                ('exhausted_at', models.DateTimeField(blank=True, null=True)),
                ('code_definition_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='enterprise_items.codedefinitionversion')),
            ],
        ),
        migrations.CreateModel(
            name='StructureDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineering_structures', to='enterprise_items.itemclassification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_structure_definitions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineering_structures', to='enterprise_items.codingorganization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_structure_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organization', 'code'],
            },
        ),
        migrations.AddField(
            model_name='codedefinition',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='code_definitions', to='enterprise_items.structuredefinition'),
        ),
        migrations.AddField(
            model_name='item',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='enterprise_items.structuredefinition'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['organization', 'structure'], name='enterprise__organiz_2bdea6_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['organization', 'code_definition'], name='enterprise__organiz_79badc_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['organization', 'code_definition_version'], name='enterprise__organiz_e2be9d_idx'),
        ),
        migrations.AddField(
            model_name='structureparameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structure_usages', to='enterprise_items.parameterdefinition'),
        ),
        migrations.AddField(
            model_name='structureparameter',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='enterprise_items.structuredefinition'),
        ),
        migrations.AddField(
            model_name='partparametervalue',
            name='structure_parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_values', to='enterprise_items.structureparameter'),
        ),
        migrations.AddField(
            model_name='technicaldatatemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_technical_data_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicaldatatemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_data_templates', to='enterprise_items.codingorganization'),
        ),
        migrations.AddField(
            model_name='technicaldatatemplate',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technical_data_templates', to='enterprise_items.structuredefinition'),
        ),
        migrations.AddField(
            model_name='technicalfielddefinition',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='enterprise_items.technicaldatatemplate'),
        ),
        migrations.AddField(
            model_name='revisiontechnicalvalue',
            name='technical_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revision_values', to='enterprise_items.technicalfielddefinition'),
        ),
        migrations.AddField(
            model_name='parttechnicalvalue',
            name='technical_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_values', to='enterprise_items.technicalfielddefinition'),
        ),
        migrations.AddIndex(
            model_name='codedefinitionversion',
            index=models.Index(fields=['code_definition', 'status'], name='enterprise__code_de_cef087_idx'),
        ),
        migrations.AddIndex(
            model_name='codedefinitionversion',
            index=models.Index(fields=['status', 'activated_at'], name='enterprise__status_39b71a_idx'),
        ),
        migrations.AddConstraint(
            model_name='codedefinitionversion',
            constraint=models.UniqueConstraint(fields=('code_definition', 'version_number'), name='uniq_code_definition_version_number'),
        ),
        migrations.AddConstraint(
            model_name='codedefinitionversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('code_definition',), name='uniq_active_version_per_code_definition'),
        ),
        migrations.AddIndex(
            model_name='parameterdefinition',
            index=models.Index(fields=['organization', 'active'], name='enterprise__organiz_febed1_idx'),
        ),
        migrations.AddIndex(
            model_name='parameterdefinition',
            index=models.Index(fields=['organization', 'code'], name='enterprise__organiz_516cc9_idx'),
        ),
        migrations.AddConstraint(
            model_name='parameterdefinition',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_parameter_code_per_org'),
        ),
        migrations.AddIndex(
            model_name='codesegment',
            index=models.Index(fields=['version', 'segment_type'], name='enterprise__version_7a8065_idx'),
        ),
        migrations.AddIndex(
            model_name='codesegment',
            index=models.Index(fields=['parameter'], name='enterprise__paramet_4e9dee_idx'),
        ),
        migrations.AddConstraint(
            model_name='codesegment',
            constraint=models.UniqueConstraint(fields=('version', 'sort_order'), name='uniq_code_segment_order'),
        ),
        migrations.AddIndex(
            model_name='parametermetadatafield',
            index=models.Index(fields=['organization', 'active'], name='enterprise__organiz_e81767_idx'),
        ),
        migrations.AddIndex(
            model_name='parametermetadatafield',
            index=models.Index(fields=['organization', 'group'], name='enterprise__organiz_a0a2f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='parametermetadatafield',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_parameter_metadata_field_code'),
        ),
        migrations.AddConstraint(
            model_name='parametermetadatavalue',
            constraint=models.UniqueConstraint(fields=('parameter', 'field_definition'), name='uniq_parameter_metadata_value'),
        ),
        migrations.AddIndex(
            model_name='parameteroption',
            index=models.Index(fields=['parameter', 'active'], name='enterprise__paramet_f2c990_idx'),
        ),
        migrations.AddConstraint(
            model_name='parameteroption',
            constraint=models.UniqueConstraint(fields=('parameter', 'stored_value'), name='uniq_parameter_option_value'),
        ),
        migrations.AddConstraint(
            model_name='parameteroption',
            constraint=models.UniqueConstraint(fields=('parameter', 'sort_order'), name='uniq_parameter_option_order'),
        ),
        migrations.AddIndex(
            model_name='codeoptionencoding',
            index=models.Index(fields=['code_segment', 'active'], name='enterprise__code_se_f52152_idx'),
        ),
        migrations.AddIndex(
            model_name='codeoptionencoding',
            index=models.Index(fields=['encoded_token'], name='enterprise__encoded_4e9d3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='codeoptionencoding',
            constraint=models.UniqueConstraint(fields=('code_segment', 'parameter_option'), name='uniq_code_option_encoding_option'),
        ),
        migrations.AddConstraint(
            model_name='codeoptionencoding',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('code_segment', 'encoded_token'), name='uniq_active_code_option_token_per_segment'),
        ),
        migrations.AddIndex(
            model_name='sequencedefinition',
            index=models.Index(fields=['code_definition_version', 'scope'], name='enterprise__code_de_9a382e_idx'),
        ),
        migrations.AddIndex(
            model_name='sequencedefinition',
            index=models.Index(fields=['exhausted_at'], name='enterprise__exhaust_aedcc1_idx'),
        ),
        migrations.AddConstraint(
            model_name='sequencedefinition',
            constraint=models.UniqueConstraint(fields=('code_definition_version', 'scope'), name='uniq_sequence_scope_per_version'),
        ),
        migrations.AddIndex(
            model_name='structuredefinition',
            index=models.Index(fields=['organization', 'active'], name='enterprise__organiz_295322_idx'),
        ),
        migrations.AddIndex(
            model_name='structuredefinition',
            index=models.Index(fields=['organization', 'status'], name='enterprise__organiz_3f3738_idx'),
        ),
        migrations.AddIndex(
            model_name='structuredefinition',
            index=models.Index(fields=['organization', 'code'], name='enterprise__organiz_fbed70_idx'),
        ),
        migrations.AddConstraint(
            model_name='structuredefinition',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_structure_code_per_org'),
        ),
        migrations.AddIndex(
            model_name='codedefinition',
            index=models.Index(fields=['organization', 'status'], name='enterprise__organiz_9f2d78_idx'),
        ),
        migrations.AddIndex(
            model_name='codedefinition',
            index=models.Index(fields=['structure', 'is_default'], name='enterprise__structu_5cb0fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='codedefinition',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_code_definition_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='codedefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('structure',), name='uniq_default_code_definition_per_structure'),
        ),
        migrations.AddIndex(
            model_name='structureparameter',
            index=models.Index(fields=['structure', 'active'], name='enterprise__structu_4bcb63_idx'),
        ),
        migrations.AddIndex(
            model_name='structureparameter',
            index=models.Index(fields=['structure', 'identity_defining'], name='enterprise__structu_b2b465_idx'),
        ),
        migrations.AddConstraint(
            model_name='structureparameter',
            constraint=models.UniqueConstraint(fields=('structure', 'parameter'), name='uniq_structure_parameter'),
        ),
        migrations.AddConstraint(
            model_name='structureparameter',
            constraint=models.UniqueConstraint(fields=('structure', 'sort_order'), name='uniq_structure_parameter_order'),
        ),
        migrations.AddIndex(
            model_name='partparametervalue',
            index=models.Index(fields=['part', 'structure_parameter'], name='enterprise__part_id_ebf2f8_idx'),
        ),
        migrations.AddIndex(
            model_name='partparametervalue',
            index=models.Index(fields=['parameter', 'normalized_value'], name='enterprise__paramet_715f1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='partparametervalue',
            constraint=models.UniqueConstraint(fields=('part', 'parameter'), name='uniq_part_parameter_value'),
        ),
        migrations.AddIndex(
            model_name='technicaldatatemplate',
            index=models.Index(fields=['organization', 'active'], name='enterprise__organiz_483f34_idx'),
        ),
        migrations.AddIndex(
            model_name='technicaldatatemplate',
            index=models.Index(fields=['structure', 'status'], name='enterprise__structu_e12b47_idx'),
        ),
        migrations.AddConstraint(
            model_name='technicaldatatemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_technical_template_code_per_org'),
        ),
        migrations.AddIndex(
            model_name='technicalfielddefinition',
            index=models.Index(fields=['template', 'scope'], name='enterprise__templat_5d9e61_idx'),
        ),
        migrations.AddIndex(
            model_name='technicalfielddefinition',
            index=models.Index(fields=['template', 'active'], name='enterprise__templat_bd2cb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='technicalfielddefinition',
            constraint=models.UniqueConstraint(fields=('template', 'code'), name='uniq_technical_field_code_per_template'),
        ),
        migrations.AddConstraint(
            model_name='technicalfielddefinition',
            constraint=models.UniqueConstraint(fields=('template', 'sort_order'), name='uniq_technical_field_order_per_template'),
        ),
        migrations.AddIndex(
            model_name='revisiontechnicalvalue',
            index=models.Index(fields=['revision'], name='enterprise__revisio_7302b3_idx'),
        ),
        migrations.AddIndex(
            model_name='revisiontechnicalvalue',
            index=models.Index(fields=['technical_field'], name='enterprise__technic_aa8b1a_idx'),
        ),
        migrations.AddConstraint(
            model_name='revisiontechnicalvalue',
            constraint=models.UniqueConstraint(fields=('revision', 'technical_field'), name='uniq_revision_technical_value'),
        ),
        migrations.AddIndex(
            model_name='parttechnicalvalue',
            index=models.Index(fields=['part'], name='enterprise__part_id_118ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='parttechnicalvalue',
            index=models.Index(fields=['technical_field'], name='enterprise__technic_8be7b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='parttechnicalvalue',
            constraint=models.UniqueConstraint(fields=('part', 'technical_field'), name='uniq_part_technical_value'),
        ),
    ]
