# Generated by Django 6.0.7 on 2026-07-20 12:03

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_items', '0006_structureparameter_technicaldatatemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='enterprise_items.codedefinition'),
        ),
        migrations.AlterField(
            model_name='item',
            name='code_definition_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='enterprise_items.codedefinitionversion'),
        ),
        migrations.AlterField(
            model_name='item',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='enterprise_items.structuredefinition'),
        ),
        migrations.AddConstraint(
            model_name='codeoptionencoding',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('encoded_token'), models.F('code_segment'), condition=models.Q(('active', True)), name='uniq_active_code_option_token_norm'),
        ),
        migrations.AddConstraint(
            model_name='codesegment',
            constraint=models.CheckConstraint(condition=models.Q(('width__isnull', True), ('width__gt', 0), _connector='OR'), name='chk_code_segment_width_positive'),
        ),
        migrations.AddConstraint(
            model_name='sequencedefinition',
            constraint=models.CheckConstraint(condition=models.Q(('starting_value__gte', 0)), name='chk_sequence_starting_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sequencedefinition',
            constraint=models.CheckConstraint(condition=models.Q(('current_value__gte', 0)), name='chk_sequence_current_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sequencedefinition',
            constraint=models.CheckConstraint(condition=models.Q(('current_value__gte', django.db.models.expressions.CombinedExpression(models.F('starting_value'), '-', models.Value(1)))), name='chk_sequence_current_not_below_start_minus_one'),
        ),
        migrations.AddConstraint(
            model_name='sequencedefinition',
            constraint=models.CheckConstraint(condition=models.Q(('width__gt', 0)), name='chk_sequence_width_positive'),
        ),
    ]
