# Generated by Django 6.0.7 on 2026-07-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_items', '0007_alter_item_code_definition_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sequencedefinition',
            name='uniq_sequence_scope_per_version',
        ),
        migrations.RemoveIndex(
            model_name='sequencedefinition',
            name='enterprise__code_de_9a382e_idx',
        ),
        migrations.AddField(
            model_name='sequencedefinition',
            name='scope_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddIndex(
            model_name='sequencedefinition',
            index=models.Index(fields=['code_definition_version', 'scope', 'scope_key'], name='enterprise__code_de_2aaf84_idx'),
        ),
        migrations.AddConstraint(
            model_name='sequencedefinition',
            constraint=models.UniqueConstraint(fields=('code_definition_version', 'scope', 'scope_key'), name='uniq_sequence_scope_key_per_version'),
        ),
    ]
