# Generated by Django 6.0.5 on 2026-06-22 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('category', models.CharField(choices=[('auth', 'احراز هویت'), ('data', 'تغییر داده'), ('business', 'عملیات کاری'), ('permission', 'دسترسی'), ('other', 'سایر')], db_index=True, default='other', max_length=20)),
                ('action', models.CharField(db_index=True, help_text='نمونه: create, update, delete, login, approve_report, lock_revision, ...', max_length=64)),
                ('target_model', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('target_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('target_repr', models.CharField(blank=True, default='', help_text='نمایشِ خوانا از هدف در زمان رویداد', max_length=255)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('request_method', models.CharField(blank=True, default='', max_length=8)),
                ('request_path', models.CharField(blank=True, default='', max_length=512)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رویداد لاگ',
                'verbose_name_plural': 'رویدادهای لاگ',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor', '-timestamp'], name='auditlog_au_actor_i_e4949d_idx'), models.Index(fields=['target_model', 'target_id'], name='auditlog_au_target__5a379d_idx'), models.Index(fields=['action', '-timestamp'], name='auditlog_au_action_db255a_idx'), models.Index(fields=['category', '-timestamp'], name='auditlog_au_categor_8e064c_idx')],
            },
        ),
    ]
