# Generated by Django 6.0.5 on 2026-06-22 08:19

import django.db.models.deletion
import ktcPlanning.validators
import mptt.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomUser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResourcePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_planning_manager_bypass_reviewer', models.BooleanField(default=False, help_text='اگر فعال باشد، مدیرِ برنامه\u200cریزی می\u200cتواند گزارش\u200cهای پروژهٔ شرکتی را بدون تاییدِ بررسی\u200cکننده مستقیماً تایید نهایی کند.', verbose_name='اجازهٔ bypass تایید بررسی\u200cکننده توسط مدیر برنامه\u200cریزی')),
            ],
            options={
                'verbose_name': 'تنظیمات سیستم',
                'verbose_name_plural': 'تنظیمات سیستم',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('scope', models.CharField(choices=[('intra_unit', 'پروژهٔ درون\u200cواحدی'), ('company', 'پروژهٔ شرکتی')], default='company', help_text='پروژه\u200cهای شرکتی نیازمندِ تاییدِ نهاییِ گزارش توسطِ مدیرِ برنامه\u200cریزی هستند.', max_length=16, verbose_name='دامنهٔ پروژه')),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='ktcPlanning.calendar')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('owner_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to='CustomUser.orgunit')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalLevelingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('is_committed', models.BooleanField(default=False, verbose_name='اعمال نهایی شده روی برنامه اصلی')),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('participating_projects', models.ManyToManyField(related_name='leveling_runs', to='ktcPlanning.project')),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='ktcPlanning.project'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(blank=True, choices=[('LABOR', 'Labor'), ('EQUIPMENT', 'Equipment'), ('MATERIAL', 'Material'), ('COST', 'Cost')], max_length=20, null=True)),
                ('max_units', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('priority', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ktcPlanning.calendar')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ktcPlanning.resourcepool')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ktcPlanning.resourcerole')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('finish_datetime', models.DateTimeField()),
                ('reason', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=False)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='ktcPlanning.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('regular_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='ktcPlanning.resource')),
            ],
            options={
                'ordering': ['effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_baseline', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_start', models.DateTimeField()),
                ('project_end', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_revisions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_revisions', to=settings.AUTH_USER_MODEL)),
                ('designated_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions_to_approve', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='ktcPlanning.project')),
            ],
            options={
                'unique_together': {('project', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseline', to='ktcPlanning.revision')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ktcPlanning.project')),
            ],
        ),
        migrations.CreateModel(
            name='SkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_level', models.IntegerField(default=1)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktcPlanning.revision')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktcPlanning.resourceskill')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktcPlanning.task')),
            ],
        ),
        migrations.CreateModel(
            name='RoleRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('required_count', models.IntegerField(default=1)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktcPlanning.revision')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktcPlanning.resourcerole')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktcPlanning.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_attachments/%Y/%m/', validators=[ktcPlanning.validators.validate_chat_file])),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_type', models.CharField(blank=True, default='', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='ktcPlanning.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TaskReportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('on-track', 'On Track'), ('at-risk', 'At Risk'), ('blocked', 'Blocked'), ('completed', 'Completed')], default='on-track', max_length=20)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('time_spent_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('notes', models.TextField(blank=True, verbose_name='Progress Notes')),
                ('blockers', models.TextField(blank=True, verbose_name='Critical Blockers')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approval_status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('reviewer_approved', 'تاییدشده توسط بررسی\u200cکننده'), ('final_approved', 'تایید نهایی'), ('rejected', 'رد شده')], default='pending', max_length=24, verbose_name='وضعیت تایید')),
                ('reviewer_approved_at', models.DateTimeField(blank=True, null=True)),
                ('final_approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False, verbose_name='وضعیت تایید (legacy)')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL)),
                ('final_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approved_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewer_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_approved_reports', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_logs', to='ktcPlanning.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TaskVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, help_text='وزن تسک در پروژه (درصد یا ضریب)', max_digits=5)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_finish', models.DateTimeField(blank=True, null=True)),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sequence', models.IntegerField(default=0, help_text='ترتیب نمایش در گانت\u200cچارت')),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ktcPlanning.calendar')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_versions', to='ktcPlanning.revision')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ktcPlanning.task')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='TaskScheduleMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('early_start', models.DateTimeField()),
                ('early_finish', models.DateTimeField()),
                ('late_start', models.DateTimeField()),
                ('late_finish', models.DateTimeField()),
                ('total_float_hours', models.IntegerField(default=0)),
                ('free_float_hours', models.IntegerField(default=0)),
                ('is_critical', models.BooleanField(default=False)),
                ('task_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='ktcPlanning.taskversion')),
            ],
        ),
        migrations.CreateModel(
            name='TaskActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_finish', models.DateTimeField(blank=True, null=True)),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actual', to='ktcPlanning.taskversion')),
            ],
        ),
        migrations.CreateModel(
            name='WBSNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs', to='ktcPlanning.project')),
            ],
        ),
        migrations.CreateModel(
            name='WBSNodeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='Planned Start Date')),
                ('planned_finish', models.DateTimeField(blank=True, null=True, verbose_name='Planned Finish Date')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ktcPlanning.wbsnode')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ktcPlanning.wbsnodeversion')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs_versions', to='ktcPlanning.revision')),
            ],
            options={
                'unique_together': {('node', 'revision'), ('revision', 'parent', 'sequence')},
            },
        ),
        migrations.AddField(
            model_name='taskversion',
            name='wbs_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ktcPlanning.wbsnodeversion'),
        ),
        migrations.CreateModel(
            name='WorkingInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='ktcPlanning.calendar')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_working', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='ktcPlanning.calendar')),
            ],
            options={
                'unique_together': {('calendar', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProjectViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_project_viewers', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='ktcPlanning.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewable_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ResourceSkillMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='ktcPlanning.resource')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktcPlanning.resourceskill')),
            ],
            options={
                'unique_together': {('resource', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='ResourceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField()),
                ('planned_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leveling_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_usages', to='ktcPlanning.globallevelingrun')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktcPlanning.resource')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktcPlanning.revision')),
            ],
            options={
                'unique_together': {('revision', 'resource', 'usage_date')},
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('FS', 'Finish-Start'), ('SS', 'Start-Start'), ('FF', 'Finish-Finish'), ('SF', 'Start-Finish')], default='FS', max_length=2)),
                ('lag_hours', models.IntegerField(default=0)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='ktcPlanning.revision')),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='ktcPlanning.task')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='ktcPlanning.task')),
            ],
            options={
                'unique_together': {('revision', 'predecessor', 'successor')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_percent', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('planned_hours', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktcPlanning.resource')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktcPlanning.revision')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktcPlanning.task')),
            ],
            options={
                'unique_together': {('revision', 'task', 'resource')},
            },
        ),
        migrations.CreateModel(
            name='TaskRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'مسئول اصلی'), ('reviewer', 'بررسی\u200cکننده'), ('executor', 'مجری'), ('project manager', 'مدیر پروژه')], max_length=20)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_roles', to='ktcPlanning.revision')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='ktcPlanning.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('revision', 'task', 'user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='TaskLevelingMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leveled_start', models.DateTimeField()),
                ('leveled_finish', models.DateTimeField()),
                ('leveling_delay_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leveling_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_metrics', to='ktcPlanning.globallevelingrun')),
                ('task_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leveling_metrics', to='ktcPlanning.taskversion')),
            ],
            options={
                'unique_together': {('leveling_run', 'task_version')},
            },
        ),
        migrations.CreateModel(
            name='VarianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('budget_at_completion', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('planned_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('earned_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('spi', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('cpi', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('schedule_variance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cost_variance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estimate_at_completion', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estimate_to_complete', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('variance_at_completion', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('action_required', models.BooleanField(default=False)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variances', to='ktcPlanning.revision')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variance_snapshots', to='ktcPlanning.task')),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('task', 'report_date', 'revision')},
            },
        ),
        migrations.AddIndex(
            model_name='taskversion',
            index=models.Index(fields=['revision', 'wbs_node'], name='ktcPlanning_revisio_46d345_idx'),
        ),
        migrations.AddIndex(
            model_name='taskversion',
            index=models.Index(fields=['planned_start'], name='ktcPlanning_planned_de6555_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskversion',
            unique_together={('task', 'revision')},
        ),
    ]
