# Generated by Django 6.0.5 on 2026-06-29 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktcPlanning', '0002_expensetype_unitofmeasure_costtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costtransaction',
            name='expense_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='costtransaction',
            name='resource_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ktcPlanning.resourcerate'),
        ),
        migrations.AlterField(
            model_name='costtransaction',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ktcPlanning.assignment'),
        ),
        migrations.AlterField(
            model_name='costtransaction',
            name='expense_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ktcPlanning.expensetype'),
        ),
    ]
