# Generated by Django 6.0.5 on 2026-06-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktcPlanning', '0003_costtransaction_expense_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costtransaction',
            name='unit_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
