# Generated by Django 6.0.5 on 2026-06-30 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
        ('ktcPlanning', '0004_alter_costtransaction_unit_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='costtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('LABOR', 'Labor'), ('MATERIAL', 'Material'), ('EQUIPMENT', 'Equipment'), ('EXPENSE', 'Expense'), ('SUBCONTRACT', 'Subcontract'), ('COST', 'Cost')], max_length=20),
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('PROJECT', 'Project'), ('WBS', 'WBS'), ('TASK', 'Task'), ('RESERVE', 'Reserve'), ('ORG_UNIT', 'Org Unit')], max_length=16)),
                ('cost_type', models.CharField(choices=[('LABOR', 'Labor'), ('MATERIAL', 'Material'), ('EQUIPMENT', 'Equipment'), ('EXPENSE', 'Expense'), ('SUBCONTRACT', 'Subcontract'), ('COST', 'Cost'), ('OVERHEAD', 'Overhead'), ('RESERVE', 'Reserve')], max_length=20)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_allocations', to='CustomUser.orgunit')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='ktcPlanning.project')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_allocations', to='ktcPlanning.revision')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_allocations', to='ktcPlanning.task')),
                ('wbs_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_allocations', to='ktcPlanning.wbsnodeversion')),
            ],
            options={
                'ordering': ['project__name', 'scope_type', 'cost_type'],
            },
        ),
        migrations.AddField(
            model_name='costtransaction',
            name='budget_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ktcPlanning.budgetallocation'),
        ),
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('CLIENT_PAYMENT', 'Client Payment'), ('INTERNAL_CAPITAL', 'Internal Capital'), ('LOAN', 'Loan'), ('CONTRACT', 'Contract'), ('GRANT', 'Grant'), ('OTHER', 'Other')], max_length=32)),
                ('source_party', models.CharField(blank=True, max_length=255)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('received_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='IRR', max_length=8)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='funding_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='ktcPlanning.fundingsource'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['project', 'scope_type'], name='ktcPlanning_project_84c136_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['project', 'cost_type'], name='ktcPlanning_project_b55c8d_idx'),
        ),
    ]
