# Generated by Django 6.0.5 on 2026-06-30 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktcPlanning', '0005_alter_costtransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetallocation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='ktcPlanning.project'),
        ),
    ]
