# Generated by Codex on 2026-07-01

import django.db.models.deletion
import ktcPlanning.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktcPlanning', '0006_alter_budgetallocation_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReportAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='task_report_attachments/%Y/%m/', validators=[ktcPlanning.validators.ChatFileValidator()])),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ktcPlanning.taskreportlog')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
