# Generated by Codex on 2026-07-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktcPlanning', '0007_taskreportattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget_allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='ktcPlanning.budgetallocation')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_consumptions', to='ktcPlanning.costtransaction')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
