# Generated by Codex on 2026-07-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktcPlanning', '0008_budgetconsumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsource',
            name='status',
            field=models.CharField(
                choices=[
                    ('DRAFT', 'Draft'),
                    ('SUBMITTED', 'Submitted'),
                    ('APPROVED', 'Approved'),
                    ('REJECTED', 'Rejected'),
                    ('LOCKED', 'Locked'),
                    ('CLOSED', 'Closed'),
                ],
                default='APPROVED',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='status',
            field=models.CharField(
                choices=[
                    ('DRAFT', 'Draft'),
                    ('SUBMITTED', 'Submitted'),
                    ('APPROVED', 'Approved'),
                    ('REJECTED', 'Rejected'),
                    ('LOCKED', 'Locked'),
                    ('CLOSED', 'Closed'),
                ],
                default='APPROVED',
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name='fundingsource',
            index=models.Index(fields=['status'], name='ktcPlanning_status_6b2170_idx'),
        ),
        migrations.AddIndex(
            model_name='fundingsource',
            index=models.Index(fields=['source_type', 'status'], name='ktcPlanning_source__fab997_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['status'], name='ktcPlanning_status_dcedfa_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['project', 'status'], name='ktcPlanning_project_0dee1f_idx'),
        ),
    ]
