# Generated by Codex on 2026-07-04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ktcPlanning', '0009_budget_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsource',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_funding_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_funding_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_funding_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budget_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_budget_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_budget_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked'), ('CLOSED', 'Closed')], default='DRAFT', max_length=16),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked'), ('CLOSED', 'Closed')], default='DRAFT', max_length=16),
        ),
    ]
