# Generated by Codex on 2026-07-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktcPlanning', '0010_budget_approval_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='parent_allocation',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='child_allocations',
                to='ktcPlanning.budgetallocation',
            ),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['parent_allocation'], name='ktcPlanning_parent__47e436_idx'),
        ),
    ]
