# Generated by Codex on 2026-07-04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ktcPlanning', '0011_budgetallocation_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetBorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SETTLED', 'Settled')], default='DRAFT', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budget_borrows', to=settings.AUTH_USER_MODEL)),
                ('from_allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrowed_out_records', to='ktcPlanning.budgetallocation')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_budget_borrows', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_budget_borrows', to=settings.AUTH_USER_MODEL)),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_budget_borrows', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_budget_borrows', to=settings.AUTH_USER_MODEL)),
                ('to_allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrowed_in_records', to='ktcPlanning.budgetallocation')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='budgetborrow',
            index=models.Index(fields=['status'], name='ktcPlanning_status_8d3f69_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetborrow',
            index=models.Index(fields=['from_allocation', 'status'], name='ktcPlanning_from_al_f41d9c_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetborrow',
            index=models.Index(fields=['to_allocation', 'status'], name='ktcPlanning_to_allo_d0a32d_idx'),
        ),
    ]
