# Generated by Codex on 2026-07-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
        ('ktcPlanning', '0012_budgetborrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='is_borrow_sink',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='budgetborrow',
            name='to_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='borrowed_in_records', to='ktcPlanning.budgetallocation'),
        ),
        migrations.AddField(
            model_name='budgetborrow',
            name='destination_cost_type',
            field=models.CharField(blank=True, choices=[('LABOR', 'Labor'), ('MATERIAL', 'Material'), ('EQUIPMENT', 'Equipment'), ('EXPENSE', 'Expense'), ('SUBCONTRACT', 'Subcontract'), ('COST', 'Cost'), ('OVERHEAD', 'Overhead'), ('RESERVE', 'Reserve')], max_length=20),
        ),
        migrations.AddField(
            model_name='budgetborrow',
            name='destination_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='budgetborrow',
            name='destination_scope_type',
            field=models.CharField(blank=True, choices=[('PROJECT', 'Project'), ('WBS', 'WBS'), ('TASK', 'Task'), ('RESERVE', 'Reserve'), ('ORG_UNIT', 'Org Unit')], max_length=16),
        ),
        migrations.AddField(
            model_name='budgetborrow',
            name='destination_org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_borrow_destinations', to='CustomUser.orgunit'),
        ),
        migrations.AddField(
            model_name='budgetborrow',
            name='destination_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_borrow_destinations', to='ktcPlanning.project'),
        ),
        migrations.AddField(
            model_name='budgetborrow',
            name='destination_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_borrow_destinations', to='ktcPlanning.revision'),
        ),
        migrations.AddField(
            model_name='budgetborrow',
            name='destination_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_borrow_destinations', to='ktcPlanning.task'),
        ),
        migrations.AddField(
            model_name='budgetborrow',
            name='destination_wbs_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_borrow_destinations', to='ktcPlanning.wbsnodeversion'),
        ),
    ]
