# Generated by Django 6.0.5 on 2026-07-04 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
        ('ktcPlanning', '0013_borrow_new_destination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnfundedForecastCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('scope_type', models.CharField(choices=[('PROJECT', 'Project'), ('WBS', 'WBS'), ('TASK', 'Task'), ('RESERVE', 'Reserve'), ('ORG_UNIT', 'Org Unit')], default='RESERVE', max_length=16)),
                ('cost_type', models.CharField(choices=[('LABOR', 'Labor'), ('MATERIAL', 'Material'), ('EQUIPMENT', 'Equipment'), ('EXPENSE', 'Expense'), ('SUBCONTRACT', 'Subcontract'), ('COST', 'Cost'), ('OVERHEAD', 'Overhead'), ('RESERVE', 'Reserve')], default='EXPENSE', max_length=20)),
                ('forecast_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('confidence', models.CharField(choices=[('ESTIMATE', 'Estimate'), ('EXPECTED', 'Expected'), ('COMMITTED', 'Committed')], default='ESTIMATE', max_length=16)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('DUE', 'Due'), ('OVERDUE', 'Overdue'), ('FUNDED', 'Funded'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_unfunded_forecast_costs', to=settings.AUTH_USER_MODEL)),
                ('linked_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_costs', to='ktcPlanning.budgetallocation')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unfunded_forecast_costs', to='CustomUser.orgunit')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unfunded_forecast_costs', to='ktcPlanning.project')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unfunded_forecast_costs', to='ktcPlanning.revision')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unfunded_forecast_costs', to='ktcPlanning.task')),
                ('wbs_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unfunded_forecast_costs', to='ktcPlanning.wbsnodeversion')),
            ],
            options={
                'ordering': ['forecast_date', 'id'],
                'indexes': [models.Index(fields=['forecast_date'], name='ktcPlanning_forecas_4a8e39_idx'), models.Index(fields=['status'], name='ktcPlanning_status_648a41_idx'), models.Index(fields=['project', 'forecast_date'], name='ktcPlanning_project_df9350_idx'), models.Index(fields=['scope_type', 'cost_type'], name='ktcPlanning_scope_t_2e7727_idx')],
            },
        ),
    ]
