# Generated by Django 6.0.6 on 2026-07-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktcPlanning', '0014_unfundedforecastcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='globallevelingrun',
            name='priority_rules',
            field=models.JSONField(blank=True, default=list, help_text='ترتیب معیارهایی که مشخص می\u200cکند وقتی چند تسک هم\u200cزمان بر سر یک منبع رقابت می\u200cکنند، کدام تسک زودتر منبع را می\u200cگیرد. مثال: [{"criterion": "total_float", "direction": "asc"}, {"criterion": "resource_priority", "direction": "asc"}]', verbose_name='معیارهای اولویت\u200cبندی تسک\u200cها'),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(default=100, help_text='در تسطیح چندپروژه\u200cای، پروژه\u200cهای با عدد کمتر اولویت بالاتری در رقابت بر سر منابع دارند.', verbose_name='اولویت پروژه'),
        ),
    ]
