# Generated by Django 6.0.6 on 2026-07-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktcPlanning', '0017_subprojectdependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='parent_schedule_warning',
            field=models.JSONField(blank=True, default=dict, help_text='آخرین تعارض تاریخ این پروژه با شبکه CPM پروژه مادر. با اجرای CPM مادر به\u200cروزرسانی می\u200cشود.', verbose_name='هشدار زمان\u200cبندی پروژه مادر'),
        ),
        migrations.AddField(
            model_name='project',
            name='parent_schedule_warning_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
