# Generated by Django 6.0.5 on 2026-07-13 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktcPlanning', '0018_project_parent_schedule_warning_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourceusage',
            unique_together={('leveling_run', 'resource', 'usage_date')},
        ),
        migrations.AddField(
            model_name='globallevelingrun',
            name='data_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globallevelingrun',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globallevelingrun',
            name='name',
            field=models.CharField(default='Untitled Leveling Plan', max_length=160),
        ),
        migrations.AddField(
            model_name='globallevelingrun',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globallevelingrun',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='globallevelingrun',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='globallevelingrun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resourceusage',
            name='capacity_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tasklevelingmetrics',
            name='decision_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tasklevelingmetrics',
            name='original_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasklevelingmetrics',
            name='original_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourceusage',
            name='revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ktcPlanning.revision'),
        ),
        migrations.CreateModel(
            name='LevelingPlanProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=100)),
                ('leveling_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_projects', to='ktcPlanning.globallevelingrun')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leveling_plan_entries', to='ktcPlanning.project')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leveling_plan_entries', to='ktcPlanning.revision')),
            ],
            options={
                'ordering': ['priority', 'project__name'],
                'unique_together': {('leveling_run', 'project')},
            },
        ),
    ]
