# Generated by Django 6.0.5 on 2026-07-14 04:01

import django.db.models.deletion
from django.db import migrations, models


def populate_official_revision_spine(apps, schema_editor):
    Project = apps.get_model('ktcPlanning', 'Project')
    Revision = apps.get_model('ktcPlanning', 'Revision')
    TaskActual = apps.get_model('ktcPlanning', 'TaskActual')
    OrgUnit = apps.get_model('CustomUser', 'OrgUnit')

    planning_manager_id = OrgUnit.objects.filter(
        is_planning_unit=True,
        manager_id__isnull=False,
    ).values_list('manager_id', flat=True).first()

    for project in Project.objects.all().iterator():
        revisions = Revision.objects.filter(
            project_id=project.pk,
            is_deleted=False,
        ).order_by('number', 'created_at')
        latest = revisions.last()
        latest_open = revisions.filter(approved_at__isnull=True).last()
        latest_approved = revisions.filter(approved_at__isnull=False).last()
        baseline = (
            revisions.filter(is_baseline=True, approved_at__isnull=False).last()
            or revisions.filter(is_baseline=True).last()
        )

        actual_row = TaskActual.objects.filter(
            task_version__revision__project_id=project.pk,
            task_version__revision__is_deleted=False,
        ).order_by('-updated_at').values_list(
            'task_version__revision_id', 'updated_at'
        ).first()
        actual_revision = revisions.filter(pk=actual_row[0]).first() if actual_row else None
        execution = actual_revision or latest_approved or latest_open or latest
        forecast = latest_approved or execution

        data_date = actual_row[1] if actual_row else project.start_date
        if project.is_deleted:
            lifecycle = 'archived'
        elif (
            baseline and baseline.approved_at
            and execution and execution.approved_at
            and data_date
        ):
            lifecycle = 'active'
        elif latest:
            lifecycle = 'planning'
        else:
            lifecycle = 'draft'

        Project.objects.filter(pk=project.pk).update(
            active_baseline_revision_id=baseline.pk if baseline else None,
            current_execution_revision_id=execution.pk if execution else None,
            current_forecast_revision_id=forecast.pk if forecast else None,
            working_revision_id=latest_open.pk if latest_open else None,
            current_data_date=data_date,
            lifecycle_status=lifecycle,
        )

        if project.scope == 'company':
            approver_id = planning_manager_id
        else:
            approver_id = None
            if project.owner_unit_id:
                approver_id = OrgUnit.objects.filter(
                    pk=project.owner_unit_id
                ).values_list('manager_id', flat=True).first()
            if not approver_id:
                creator_unit_id = getattr(project.created_by, 'unit_id', None)
                if creator_unit_id:
                    approver_id = OrgUnit.objects.filter(
                        pk=creator_unit_id
                    ).values_list('manager_id', flat=True).first()
        approver_id = approver_id or project.created_by_id
        revisions.filter(approved_at__isnull=True).update(
            designated_approver_id=approver_id
        )


def clear_official_revision_spine(apps, schema_editor):
    Project = apps.get_model('ktcPlanning', 'Project')
    Project.objects.update(
        active_baseline_revision_id=None,
        current_execution_revision_id=None,
        current_forecast_revision_id=None,
        working_revision_id=None,
        current_data_date=None,
        lifecycle_status='draft',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ktcPlanning', '0019_alter_resourceusage_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active_baseline_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baseline_for_projects', to='ktcPlanning.revision'),
        ),
        migrations.AddField(
            model_name='project',
            name='current_data_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='current_execution_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execution_for_projects', to='ktcPlanning.revision'),
        ),
        migrations.AddField(
            model_name='project',
            name='current_forecast_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forecast_for_projects', to='ktcPlanning.revision'),
        ),
        migrations.AddField(
            model_name='project',
            name='lifecycle_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='working_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='working_for_projects', to='ktcPlanning.revision'),
        ),
        migrations.RunPython(populate_official_revision_spine, clear_official_revision_spine),
    ]