# Generated by Codex for task financial plans.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ktcPlanning', '0022_variancereport_report_date_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFinancialPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('payable', 'Payable'), ('receivable', 'Receivable')], max_length=16)),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='IRR', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_financial_plans', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_plans', to='ktcPlanning.task')),
            ],
            options={
                'ordering': ['task_id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sequence', models.PositiveIntegerField()),
                ('trigger_type', models.CharField(choices=[('before_start', 'Before start'), ('approved_progress', 'Approved progress'), ('task_completion', 'Task completion'), ('before_delivery', 'Before delivery'), ('fixed_date', 'Fixed date'), ('manual', 'Manual')], max_length=32)),
                ('amount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=16)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('progress_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('blocks_task_start', models.BooleanField(default=False)),
                ('blocks_task_delivery', models.BooleanField(default=False)),
                ('blocks_progress_after_threshold', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('eligible', 'Eligible'), ('invoiced', 'Invoiced'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='locked', max_length=24)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestones', to='ktcPlanning.taskfinancialplan')),
            ],
            options={
                'ordering': ['financial_plan', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('transaction_date', models.DateField()),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_transactions', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ktcPlanning.paymentmilestone')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at', '-id'],
            },
        ),
        migrations.AddIndex(model_name='taskfinancialplan', index=models.Index(fields=['task', 'status'], name='ktcPlanning_task_id_4e339b_idx')),
        migrations.AddIndex(model_name='taskfinancialplan', index=models.Index(fields=['status'], name='ktcPlanning_status_b1fb1b_idx')),
        migrations.AddConstraint(model_name='taskfinancialplan', constraint=models.CheckConstraint(condition=models.Q(('contract_amount__gt', 0)), name='task_financial_plan_amount_positive')),
        migrations.AddConstraint(model_name='taskfinancialplan', constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('task',), name='one_active_financial_plan_per_task')),
        migrations.AddIndex(model_name='paymentmilestone', index=models.Index(fields=['financial_plan', 'status'], name='ktcPlanning_financi_874184_idx')),
        migrations.AddIndex(model_name='paymentmilestone', index=models.Index(fields=['status'], name='ktcPlanning_status_bbc8f2_idx')),
        migrations.AddIndex(model_name='paymentmilestone', index=models.Index(fields=['due_date'], name='ktcPlanning_due_dat_c59edc_idx')),
        migrations.AddConstraint(model_name='paymentmilestone', constraint=models.UniqueConstraint(fields=('financial_plan', 'sequence'), name='unique_financial_milestone_sequence')),
        migrations.AddConstraint(model_name='paymentmilestone', constraint=models.CheckConstraint(condition=models.Q(('percentage__isnull', True), models.Q(('percentage__gt', 0), ('percentage__lte', 100)), _connector='OR'), name='payment_milestone_percentage_range')),
        migrations.AddConstraint(model_name='paymentmilestone', constraint=models.CheckConstraint(condition=models.Q(('progress_threshold__isnull', True), models.Q(('progress_threshold__gte', 0), ('progress_threshold__lte', 100)), _connector='OR'), name='payment_milestone_progress_range')),
        migrations.AddConstraint(model_name='paymentmilestone', constraint=models.CheckConstraint(condition=models.Q(('fixed_amount__isnull', True), ('fixed_amount__gt', 0), _connector='OR'), name='payment_milestone_fixed_amount_positive')),
        migrations.AddIndex(model_name='paymenttransaction', index=models.Index(fields=['milestone', 'transaction_date'], name='ktcPlanning_milesto_b27743_idx')),
        migrations.AddIndex(model_name='paymenttransaction', index=models.Index(fields=['transaction_date'], name='ktcPlanning_transac_56ea75_idx')),
        migrations.AddIndex(model_name='paymenttransaction', index=models.Index(fields=['transaction_type'], name='ktcPlanning_transac_c39671_idx')),
        migrations.AddConstraint(model_name='paymenttransaction', constraint=models.CheckConstraint(condition=models.Q(('transaction_type', 'adjustment'), ('amount__gt', 0), _connector='OR'), name='payment_refund_amount_positive')),
    ]