# Generated by Codex for task financial plan cost transaction links.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ktcPlanning', '0023_task_financial_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfinancialplan',
            name='cost_transaction',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='financial_plans',
                to='ktcPlanning.costtransaction',
            ),
        ),
    ]