# Generated by Codex for direct COST transaction amount semantics.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktcPlanning', '0024_taskfinancialplan_cost_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costtransaction',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=14, null=True),
        ),
    ]
