# Generated by Django 6.0.6 on 2026-07-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktcPlanning', '0030_taskdeliveryattachment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variancereport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='variancereport',
            name='dimension',
            field=models.CharField(choices=[('effort', 'Effort'), ('cost', 'Cost')], db_index=True, default='effort', max_length=16),
        ),
        migrations.AddIndex(
            model_name='variancereport',
            index=models.Index(fields=['task', 'dimension', 'report_date'], name='variance_task_dim_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='variancereport',
            constraint=models.UniqueConstraint(fields=('task', 'revision', 'report_date', 'dimension'), name='unique_variance_report_task_revision_date_dimension'),
        ),
    ]
