# Generated by Codex on 2026-07-26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ktcPlanning", "0031_variance_report_dimension"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=8, unique=True)),
                ("name", models.CharField(max_length=64)),
                ("symbol", models.CharField(blank=True, max_length=16)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_currency", models.CharField(max_length=8)),
                ("target_currency", models.CharField(max_length=8)),
                ("rate", models.DecimalField(decimal_places=10, max_digits=24)),
                ("effective_date", models.DateField()),
                ("source", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-effective_date", "-created_at", "-id"]},
        ),
        migrations.AddField(
            model_name="costtransaction",
            name="currency",
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="currency",
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="variancereport",
            name="currency",
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
        migrations.RemoveConstraint(
            model_name="variancereport",
            name="unique_variance_report_task_revision_date_dimension",
        ),
        migrations.AddIndex(
            model_name="exchangerate",
            index=models.Index(fields=["source_currency", "target_currency", "effective_date"], name="ktcPlanning_source__79cddd_idx"),
        ),
        migrations.AddIndex(
            model_name="exchangerate",
            index=models.Index(fields=["effective_date"], name="ktcPlanning_effecti_ae588f_idx"),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.CheckConstraint(condition=models.Q(rate__gt=0), name="exchange_rate_positive"),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.CheckConstraint(condition=~models.Q(source_currency=models.F("target_currency")), name="exchange_rate_source_target_differ"),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.UniqueConstraint(fields=("source_currency", "target_currency", "effective_date"), name="unique_exchange_rate_pair_date"),
        ),
        migrations.AddConstraint(
            model_name="variancereport",
            constraint=models.UniqueConstraint(condition=models.Q(dimension="effort"), fields=("task", "revision", "report_date", "dimension"), name="unique_effort_variance_report_task_revision_date"),
        ),
        migrations.AddConstraint(
            model_name="variancereport",
            constraint=models.UniqueConstraint(condition=models.Q(currency__isnull=False, dimension="cost"), fields=("task", "revision", "report_date", "dimension", "currency"), name="unique_cost_variance_report_task_revision_date_currency"),
        ),
    ]
