# Generated by Django 6.0.5 on 2026-08-01 06:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktcPlanning', '0033_phase14_project_opc_erp_integration'),
        ('opc', '0017_phase15_procurement_cost_performance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOPCImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opc_graph_version', models.PositiveBigIntegerField(default=0)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied')], default='APPLIED', max_length=20)),
                ('operation_task_map', models.JSONField(blank=True, default=dict)),
                ('resource_assignment_map', models.JSONField(blank=True, default=dict)),
                ('dependency_map', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_project_opc_imports', to=settings.AUTH_USER_MODEL)),
                ('created_wbs_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_opc_imports', to='ktcPlanning.wbsnodeversion')),
                ('opc_diagram', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_imports', to='opc.opcdiagram')),
                ('parent_wbs_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opc_imports', to='ktcPlanning.wbsnodeversion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opc_imports', to='ktcPlanning.project')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opc_imports', to='ktcPlanning.revision')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'revision'], name='ktcPlanning_project_0d233d_idx'), models.Index(fields=['opc_diagram', 'opc_graph_version'], name='ktcPlanning_opc_dia_21af16_idx')],
                'unique_together': {('revision', 'parent_wbs_node', 'opc_diagram', 'idempotency_key')},
            },
        ),
    ]
