# Generated by Django 6.0.6 on 2026-08-01 04:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeResolutionAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload_version', models.CharField(max_length=20)),
                ('object_type', models.CharField(max_length=120)),
                ('object_id', models.CharField(max_length=120)),
                ('success', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('request_id', models.CharField(blank=True, max_length=80)),
                ('correlation_id', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_resolution_audits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(max_length=80)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.CharField(max_length=40)),
                ('schema_name', models.CharField(max_length=80)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('DRY_RUN', 'Dry run'), ('VALIDATED', 'Validated'), ('APPLIED', 'Applied'), ('FAILED', 'Failed')], default='DRY_RUN', max_length=20)),
                ('dry_run', models.BooleanField(default=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('valid_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('schema_name', 'idempotency_key')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationOutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=120, unique=True)),
                ('event_type', models.CharField(max_length=120)),
                ('schema_version', models.CharField(default='v1', max_length=40)),
                ('aggregate_type', models.CharField(max_length=120)),
                ('aggregate_id', models.CharField(max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('DEAD_LETTER', 'Dead letter')], default='PENDING', max_length=30)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, max_length=80)),
                ('command_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='release_rea_status_02a82e_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='release_rea_aggrega_fc2d3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportJobRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='release_readiness.importjob')),
            ],
            options={
                'ordering': ['job', 'row_number'],
                'unique_together': {('job', 'row_number')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('object_type', models.CharField(blank=True, max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=120)),
                ('dedupe_key', models.CharField(blank=True, max_length=160)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_at', models.DateTimeField(blank=True, null=True)),
                ('email_provider_state', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='release_rea_recipie_4d3933_idx'), models.Index(fields=['category', 'severity'], name='release_rea_categor_e5051b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('recipient', 'dedupe_key'), name='unique_notification_dedupe')],
            },
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=80)),
                ('object_type', models.CharField(blank=True, max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category', 'object_type', 'object_id')},
            },
        ),
    ]
