# Generated by Django 6.0.6 on 2026-08-01 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release_readiness', '0001_phase16_release_readiness_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='release_rea_recipie_12ee07_idx'),
        ),
    ]
