"""
Django settings for KTCProject project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.contrib.auth.context_processors import auth

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a local .env file (if present).
# Keeps secrets and DB credentials out of the codebase.
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    # python-dotenv is optional; env vars can also be set by the shell.
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: در production حتماً باید از environment variable تنظیم شود.
# در حالت development اگر متغیر تنظیم نشده باشد، یک خطای واضح نمایش داده می‌شود
# تا توسعه‌دهنده مجبور شود فایل .env را تنظیم کند.
_secret_key_env = os.environ.get('DJANGO_SECRET_KEY', '').strip()
if not _secret_key_env:
    import sys
    # در محیط تست (pytest) یک مقدار موقت می‌دهیم تا تست‌ها کار کنند
    if 'pytest' in sys.modules or 'test' in sys.argv:
        _secret_key_env = 'test-secret-key-only-for-testing-never-use-in-production'
    else:
        raise RuntimeError(
            "\n\n"
            "❌ DJANGO_SECRET_KEY تنظیم نشده است!\n"
            "   لطفاً فایل .env را از روی .env.example بسازید و مقدار آن را تنظیم کنید:\n"
            "   cp .env.example .env\n"
            "   سپس DJANGO_SECRET_KEY را با یک رشته تصادفی طولانی پر کنید.\n"
            "   برای تولید کلید: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\"\n"
        )
SECRET_KEY = _secret_key_env

# DEBUG: defaults to True for local dev. Set DJANGO_DEBUG=0 in production.
DEBUG = os.environ.get('DJANGO_DEBUG', '1').lower() not in ('0', 'false', 'no')

# ALLOWED_HOSTS: comma-separated list via env. Falls back to permissive in dev.
_allowed_hosts_env = os.environ.get('DJANGO_ALLOWED_HOSTS', '').strip()
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = ["*"] if DEBUG else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ktcPlanning.apps.KtcplanningConfig',
    'CustomUser.apps.CustomuserConfig',
    'auditlog.apps.AuditlogConfig',
    'corsheaders',
    "rest_framework_simplejwt.token_blacklist",
    'management_reports.apps.ManagementReportsConfig'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'auditlog.middleware.AuditMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'KTCProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'KTCProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# DB_ENGINE selects the backend:
#   - "postgres" / "postgresql"  -> django.db.backends.postgresql  (default)
#   - "sqlite"                   -> django.db.backends.sqlite3     (legacy/local fallback)
# All connection params are read from environment variables; sensible defaults are used
# for local development.

_DB_ENGINE = os.environ.get('DB_ENGINE', 'postgres').lower()

if _DB_ENGINE in ('sqlite', 'sqlite3'):
    print('sqlitttttt')
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE':       'django.db.backends.postgresql',
            'NAME':         os.environ.get('POSTGRES_DB',       'noviraDB'),
            'USER':         os.environ.get('POSTGRES_USER',     'erfanAdmin'),
            'PASSWORD':     os.environ.get('POSTGRES_PASSWORD', 'erfan315'),
            'HOST':         os.environ.get('POSTGRES_HOST',     '127.0.0.1'),
            'PORT':         os.environ.get('POSTGRES_PORT',     '5432'),
            # Persistent connections for better performance under load.
            'CONN_MAX_AGE': int(os.environ.get('POSTGRES_CONN_MAX_AGE', '60')),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTH_USER_MODEL = 'CustomUser.CustomUser'

CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# اجازه دادن به ارسال cookie در cross-origin requests (لازم برای httpOnly Cookie auth)
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# تنظیمات امنیتی Cookie
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False   # False تا فرانت‌اند بتواند آن را بخواند و در header بفرستد
CSRF_COOKIE_SAMESITE = 'Lax'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # ابتدا از httpOnly Cookie می‌خواند، سپس fallback به Authorization header
        'CustomUser.authentication.CookieJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Throttling: scoped + reasonable defaults. View-level throttle_scope is honored.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon':     '60/min',
        'user':     '2000/min',
        'register': '5/min',   # public registration is rate-limited per IP
        'login':    '10/min',  # apply via throttle_scope on token-obtain views if added
    },
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':  timedelta(days=1),     # کوتاه‌سازی به ۳۰ دقیقه در آینده، پس از فعال‌سازیِ refresh interceptor در فرانت
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # rotation + blacklist: هر بار که refresh استفاده می‌شود، توکنِ قبلی باطل و جدیدی صادر می‌شود.
    'ROTATE_REFRESH_TOKENS':       True,
    'BLACKLIST_AFTER_ROTATION':    True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME':  'HTTP_AUTHORIZATION',
}

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization', # این مهم‌ترین بخش است!
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

APPEND_SLASH=False