# Generated by Django 6.0.5 on 2026-06-28 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ktcPlanning', '0002_expensetype_unitofmeasure_costtransaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_progress', models.DecimalField(decimal_places=2, max_digits=5)),
                ('planner_summary', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_reports', to='ktcPlanning.project')),
            ],
        ),
        migrations.CreateModel(
            name='CuratedBottleneck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(default='high', max_length=20)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ktcPlanning.task')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottlenecks', to='management_reports.managementreport')),
            ],
        ),
    ]
