# Generated by Django 6.0.5 on 2026-06-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedbottleneck',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='آیا دستی اضافه شده؟'),
        ),
        migrations.AddField(
            model_name='curatedbottleneck',
            name='planner_remark',
            field=models.TextField(blank=True, verbose_name='تحلیل و راهکار برنامه\u200cریز'),
        ),
        migrations.AlterField(
            model_name='curatedbottleneck',
            name='description',
            field=models.TextField(verbose_name='شرح مشکل (تولید شده توسط سیستم یا کاربر)'),
        ),
    ]
