# Generated by Django 6.0.5 on 2026-06-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_reports', '0002_curatedbottleneck_is_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
