# Generated by Django 6.0.5 on 2026-08-01 05:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomUser', '0001_initial'),
        ('ktcPlanning', '0033_phase14_project_opc_erp_integration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReminderEscalationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('upcoming_deadline_days', models.PositiveIntegerField(default=3)),
                ('progress_report_due_days', models.PositiveIntegerField(default=7)),
                ('overdue_escalation_days', models.PositiveIntegerField(default=1)),
                ('higher_escalation_days', models.PositiveIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('confidentiality', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], default='internal', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('chairperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_committees', to=settings.AUTH_USER_MODEL)),
                ('owning_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_committees', to='CustomUser.orgunit')),
                ('secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_committees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(default='member', max_length=50)),
                ('can_view_confidential', models.BooleanField(default=False)),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='meeting_management.committee')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CustomUser.orgunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['committee', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_number', models.CharField(blank=True, max_length=80, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('planned_start', models.DateTimeField()),
                ('planned_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('online_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('held', 'Held'), ('minutes_drafting', 'Minutes drafting'), ('in_review', 'In review'), ('approved', 'Approved'), ('archived', 'Archived'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('confidentiality', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], default='internal', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('approval_workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meeting_management.approvalworkflow')),
                ('chairperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chaired_meetings', to=settings.AUTH_USER_MODEL)),
                ('committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='meeting_management.committee')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_meetings', to=settings.AUTH_USER_MODEL)),
                ('owning_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_meetings', to='CustomUser.orgunit')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='ktcPlanning.project')),
                ('secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secretary_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-planned_start', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('planned_duration_minutes', models.PositiveIntegerField(default=15)),
                ('discussion_notes', models.TextField(blank=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='meeting_management.meeting')),
                ('presenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['meeting', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='MeetingMinutesVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('revision_requested', 'Revision requested'), ('superseded', 'Superseded')], default='draft', max_length=30)),
                ('is_current', models.BooleanField(default=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('participant_snapshot', models.JSONField(blank=True, default=list)),
                ('decision_snapshot', models.JSONField(blank=True, default=list)),
                ('resolution_snapshot', models.JSONField(blank=True, default=list)),
                ('final_document_checksum', models.CharField(blank=True, max_length=128)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_minute_versions', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_minute_versions', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minute_versions', to='meeting_management.meeting')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_minute_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['meeting', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='MeetingSeries',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('recurrence_rule', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series', to='meeting_management.committee')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_meeting_series', to=settings.AUTH_USER_MODEL)),
                ('owning_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_series', to='CustomUser.orgunit')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='meeting_management.meetingseries'),
        ),
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_confidentiality', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], default='internal', max_length=20)),
                ('requires_minutes_approval', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'code'], name='meeting_man_is_acti_4ba3dd_idx')],
            },
        ),
        migrations.AddField(
            model_name='meetingseries',
            name='meeting_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='meeting_management.meetingtype'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='meeting_management.meetingtype'),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='meeting_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meeting_management.meetingtype'),
        ),
        migrations.CreateModel(
            name='MeetingUnitInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participation_mode', models.CharField(choices=[('manager', 'Manager'), ('representative', 'Representative'), ('all_members', 'All members')], default='representative', max_length=20)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('delegated', 'Delegated'), ('cancelled', 'Cancelled')], default='invited', max_length=20)),
                ('represented_unit_name', models.CharField(blank=True, max_length=255)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_invitations', to='meeting_management.meeting')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_invitations', to='CustomUser.orgunit')),
            ],
            options={
                'ordering': ['meeting', 'unit_id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_name', models.CharField(blank=True, max_length=255)),
                ('external_email', models.EmailField(blank=True, max_length=254)),
                ('represented_unit_name', models.CharField(blank=True, max_length=255)),
                ('invitation_status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('delegated', 'Delegated'), ('cancelled', 'Cancelled')], default='invited', max_length=20)),
                ('attendance_status', models.CharField(choices=[('unknown', 'Unknown'), ('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('left_early', 'Left early'), ('online', 'Online')], default='unknown', max_length=20)),
                ('can_view_confidential', models.BooleanField(default=False)),
                ('delegated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_delegations', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meeting_management.meeting')),
                ('represented_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CustomUser.orgunit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meeting_participations', to=settings.AUTH_USER_MODEL)),
                ('invited_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='meeting_management.meetingunitinvitation')),
            ],
            options={
                'ordering': ['meeting', 'user_id', 'external_name'],
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='reminder_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meeting_management.reminderescalationpolicy'),
        ),
        migrations.CreateModel(
            name='ApprovalWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('role', models.CharField(max_length=50)),
                ('required', models.BooleanField(default=True)),
                ('escalation_after_hours', models.PositiveIntegerField(default=48)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='meeting_management.approvalworkflow')),
            ],
            options={
                'ordering': ['workflow', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('workflow', 'sequence'), name='mm_unique_workflow_step_sequence')],
            },
        ),
        migrations.AddIndex(
            model_name='committee',
            index=models.Index(fields=['owning_unit', 'is_active'], name='meeting_man_owning__874f45_idx'),
        ),
        migrations.AddIndex(
            model_name='committee',
            index=models.Index(fields=['confidentiality'], name='meeting_man_confide_ef9837_idx'),
        ),
        migrations.AddIndex(
            model_name='committeemembership',
            index=models.Index(fields=['committee', 'is_active'], name='meeting_man_committ_229ecf_idx'),
        ),
        migrations.AddConstraint(
            model_name='committeemembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('committee', 'user'), name='mm_unique_active_committee_member'),
        ),
        migrations.AddConstraint(
            model_name='committeemembership',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='mm_committee_member_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='meetingagendaitem',
            constraint=models.UniqueConstraint(fields=('meeting', 'sequence'), name='mm_unique_agenda_sequence'),
        ),
        migrations.AddConstraint(
            model_name='meetingagendaitem',
            constraint=models.CheckConstraint(condition=models.Q(('planned_duration_minutes__gt', 0)), name='mm_agenda_duration_positive'),
        ),
        migrations.AddIndex(
            model_name='meetingminutesversion',
            index=models.Index(fields=['meeting', 'status'], name='meeting_man_meeting_f286c0_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingminutesversion',
            index=models.Index(fields=['status', 'approved_at'], name='meeting_man_status_8783ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingminutesversion',
            constraint=models.UniqueConstraint(fields=('meeting', 'version_number'), name='mm_unique_minutes_version'),
        ),
        migrations.AddConstraint(
            model_name='meetingminutesversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('meeting',), name='mm_one_current_minutes_version'),
        ),
        migrations.AddConstraint(
            model_name='meetingminutesversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gt', 0)), name='mm_minutes_version_positive'),
        ),
        migrations.AddIndex(
            model_name='meetingseries',
            index=models.Index(fields=['meeting_type', 'is_active'], name='meeting_man_meeting_eb3d19_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingseries',
            index=models.Index(fields=['owning_unit', 'is_active'], name='meeting_man_owning__da86ee_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingunitinvitation',
            index=models.Index(fields=['unit', 'status'], name='meeting_man_unit_id_28175f_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingunitinvitation',
            constraint=models.UniqueConstraint(fields=('meeting', 'unit'), name='mm_unique_meeting_unit_invitation'),
        ),
        migrations.AddIndex(
            model_name='meetingparticipant',
            index=models.Index(fields=['meeting', 'attendance_status'], name='meeting_man_meeting_8b7127_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingparticipant',
            index=models.Index(fields=['user', 'invitation_status'], name='meeting_man_user_id_a8a630_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingparticipant',
            index=models.Index(fields=['represented_unit', 'meeting'], name='meeting_man_represe_ac28ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('meeting', 'user'), name='mm_unique_meeting_user_participant'),
        ),
        migrations.AddConstraint(
            model_name='meetingparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('external_name', ''), _negated=True), _connector='OR'), name='mm_participant_has_user_or_external_name'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status', 'planned_start'], name='meeting_man_status_c0c58e_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['meeting_type', 'planned_start'], name='meeting_man_meeting_4d28aa_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['committee', 'planned_start'], name='meeting_man_committ_e6796c_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['project', 'planned_start'], name='meeting_man_project_b33cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['owning_unit', 'planned_start'], name='meeting_man_owning__81e45e_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['confidentiality'], name='meeting_man_confide_180b15_idx'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.CheckConstraint(condition=models.Q(('planned_end__gt', models.F('planned_start'))), name='mm_meeting_planned_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.CheckConstraint(condition=models.Q(('actual_end__isnull', True), ('actual_start__isnull', True), ('actual_end__gt', models.F('actual_start')), _connector='OR'), name='mm_meeting_actual_end_after_start'),
        ),
    ]
