# Generated by Django 6.0.6 on 2026-08-01 05:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
        ('ktcPlanning', '0033_phase14_project_opc_erp_integration'),
        ('meeting_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confidentiality', models.CharField(blank=True, choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], max_length=20)),
                ('agenda_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='meeting_management.meetingagendaitem')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='meeting_management.meeting')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_meeting_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['meeting', 'decision_number'],
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolution_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('confidentiality', models.CharField(blank=True, choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolutions', to='meeting_management.meetingdecision')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='meeting_management.meeting')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_resolutions', to=settings.AUTH_USER_MODEL)),
                ('owner_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_resolutions', to='CustomUser.orgunit')),
            ],
            options={
                'ordering': ['meeting', 'resolution_number'],
            },
        ),
        migrations.CreateModel(
            name='ResolutionAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('original_due_date', models.DateField()),
                ('current_due_date', models.DateField()),
                ('completion_criteria', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('not_started', 'Not started'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('submitted_for_review', 'Submitted for review'), ('revision_requested', 'Revision requested'), ('accepted', 'Accepted'), ('closed', 'Closed'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('confidentiality', models.CharField(blank=True, choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], max_length=20)),
                ('execution_mode', models.CharField(choices=[('standalone', 'Standalone'), ('project_linked', 'Project linked'), ('project_task', 'Project task')], default='standalone', max_length=20)),
                ('blocked_reason', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('accountable_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accountable_meeting_actions', to='CustomUser.orgunit')),
                ('accountable_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accountable_meeting_actions', to=settings.AUTH_USER_MODEL)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approve_meeting_actions', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_meeting_actions', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_actions', to='meeting_management.resolutionaction')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meeting_actions', to='ktcPlanning.project')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='meeting_management.resolution')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_meeting_actions', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_meeting_actions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meeting_actions', to='ktcPlanning.task')),
            ],
            options={
                'ordering': ['resolution', 'action_number'],
            },
        ),
        migrations.CreateModel(
            name='MeetingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('dismissed', 'Dismissed')], default='unread', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meeting_management.meeting')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_notifications', to=settings.AUTH_USER_MODEL)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meeting_management.resolutionaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='active', max_length=30)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='meeting_management.meeting')),
                ('minute_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='meeting_management.meetingminutesversion')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='meeting_management.approvalworkflow')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='meeting_management.resolutionaction')),
            ],
        ),
        migrations.CreateModel(
            name='ActionProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporting_date', models.DateField(default=django.utils.timezone.localdate)),
                ('progress_percent', models.PositiveSmallIntegerField()),
                ('work_completed', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('blockers', models.TextField(blank=True)),
                ('support_required', models.TextField(blank=True)),
                ('forecast_completion_date', models.DateField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_progress_reports', to=settings.AUTH_USER_MODEL)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='meeting_management.resolutionaction')),
            ],
            options={
                'ordering': ['action', '-reporting_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependency_type', models.CharField(choices=[('finish_to_start', 'Finish to start'), ('approval_required', 'Approval required'), ('information_required', 'Information required')], default='finish_to_start', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_dependencies', to='meeting_management.resolutionaction')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_dependencies', to='meeting_management.resolutionaction')),
            ],
            options={
                'ordering': ['successor', 'predecessor'],
            },
        ),
        migrations.CreateModel(
            name='ActionDeadlineChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_due_date_at_request', models.DateField()),
                ('requested_due_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_deadline_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_deadline_requests', to=settings.AUTH_USER_MODEL)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_change_requests', to='meeting_management.resolutionaction')),
            ],
            options={
                'ordering': ['action', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionCompletionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('revision_requested', 'Revision requested'), ('rejected', 'Rejected')], default='submitted', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_completion_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_completion_submissions', to=settings.AUTH_USER_MODEL)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_submissions', to='meeting_management.resolutionaction')),
            ],
            options={
                'ordering': ['action', '-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('new_accountable_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='CustomUser.orgunit')),
                ('new_accountable_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('new_responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('previous_accountable_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='CustomUser.orgunit')),
                ('previous_accountable_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('previous_responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='meeting_management.resolutionaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResolutionActionRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('accountable', 'Accountable'), ('responsible', 'Responsible'), ('reviewer', 'Reviewer'), ('approver', 'Approver'), ('contributor', 'Contributor'), ('informed', 'Informed')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='meeting_management.resolutionaction')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_action_roles', to='CustomUser.orgunit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_action_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['action', 'role', 'user_id', 'unit_id'],
            },
        ),
        migrations.CreateModel(
            name='ActionEvidenceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='meeting_action_evidence/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('completion_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_attachments', to='meeting_management.actioncompletionsubmission')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('progress_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_attachments', to='meeting_management.actionprogressreport')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('progress_report__isnull', False), ('completion_submission__isnull', False), _connector='OR'), name='mm_evidence_has_parent')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflowTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_workflow_tasks', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='meeting_management.approvalworkflowinstance')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meeting_management.approvalworkflowstep')),
            ],
            options={
                'ordering': ['instance', 'step__sequence'],
                'indexes': [models.Index(fields=['assigned_to', 'status'], name='meeting_man_assigne_9d7fd9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='meetingdecision',
            index=models.Index(fields=['meeting', 'decided_at'], name='meeting_man_meeting_a11bd7_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingdecision',
            constraint=models.UniqueConstraint(fields=('meeting', 'decision_number'), name='mm_unique_decision_number'),
        ),
        migrations.AddConstraint(
            model_name='meetingdecision',
            constraint=models.CheckConstraint(condition=models.Q(('decision_number__gt', 0)), name='mm_decision_number_positive'),
        ),
        migrations.AddIndex(
            model_name='resolution',
            index=models.Index(fields=['status', 'priority'], name='meeting_man_status_81f29c_idx'),
        ),
        migrations.AddIndex(
            model_name='resolution',
            index=models.Index(fields=['owner_unit', 'status'], name='meeting_man_owner_u_5a73a0_idx'),
        ),
        migrations.AddIndex(
            model_name='resolution',
            index=models.Index(fields=['confidentiality'], name='meeting_man_confide_ec20ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='resolution',
            constraint=models.UniqueConstraint(fields=('meeting', 'resolution_number'), name='mm_unique_resolution_number'),
        ),
        migrations.AddConstraint(
            model_name='resolution',
            constraint=models.CheckConstraint(condition=models.Q(('resolution_number__gt', 0)), name='mm_resolution_number_positive'),
        ),
        migrations.AddIndex(
            model_name='resolutionaction',
            index=models.Index(fields=['status', 'current_due_date'], name='meeting_man_status_75400b_idx'),
        ),
        migrations.AddIndex(
            model_name='resolutionaction',
            index=models.Index(fields=['accountable_unit', 'status'], name='meeting_man_account_4a333c_idx'),
        ),
        migrations.AddIndex(
            model_name='resolutionaction',
            index=models.Index(fields=['accountable_user', 'status'], name='meeting_man_account_43dc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='resolutionaction',
            index=models.Index(fields=['responsible_user', 'status'], name='meeting_man_respons_c02c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='resolutionaction',
            index=models.Index(fields=['reviewer', 'status'], name='meeting_man_reviewe_601879_idx'),
        ),
        migrations.AddIndex(
            model_name='resolutionaction',
            index=models.Index(fields=['project', 'status'], name='meeting_man_project_380fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='resolutionaction',
            index=models.Index(fields=['confidentiality'], name='meeting_man_confide_202156_idx'),
        ),
        migrations.AddConstraint(
            model_name='resolutionaction',
            constraint=models.UniqueConstraint(fields=('resolution', 'action_number'), name='mm_unique_resolution_action_number'),
        ),
        migrations.AddConstraint(
            model_name='resolutionaction',
            constraint=models.CheckConstraint(condition=models.Q(('action_number__gt', 0)), name='mm_action_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='resolutionaction',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percent__gte', 0), ('progress_percent__lte', 100)), name='mm_action_progress_range'),
        ),
        migrations.AddConstraint(
            model_name='resolutionaction',
            constraint=models.CheckConstraint(condition=models.Q(('planned_start__isnull', True), ('original_due_date__gte', models.F('planned_start')), _connector='OR'), name='mm_action_original_due_after_start'),
        ),
        migrations.AddConstraint(
            model_name='resolutionaction',
            constraint=models.CheckConstraint(condition=models.Q(('planned_start__isnull', True), ('current_due_date__gte', models.F('planned_start')), _connector='OR'), name='mm_action_current_due_after_start'),
        ),
        migrations.AddIndex(
            model_name='meetingnotification',
            index=models.Index(fields=['recipient', 'status'], name='meeting_man_recipie_824a99_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingnotification',
            index=models.Index(fields=['notification_type', 'created_at'], name='meeting_man_notific_455c4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingnotification',
            constraint=models.UniqueConstraint(fields=('recipient', 'idempotency_key'), name='mm_unique_notification_idempotency'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflowinstance',
            index=models.Index(fields=['status', 'created_at'], name='meeting_man_status_c84a98_idx'),
        ),
        migrations.AddIndex(
            model_name='actionprogressreport',
            index=models.Index(fields=['reporter', 'reporting_date'], name='meeting_man_reporte_b0b64b_idx'),
        ),
        migrations.AddIndex(
            model_name='actionprogressreport',
            index=models.Index(fields=['action', 'reporting_date'], name='meeting_man_action__bd43c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='actionprogressreport',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percent__gte', 0), ('progress_percent__lte', 100)), name='mm_report_progress_range'),
        ),
        migrations.AddIndex(
            model_name='actiondependency',
            index=models.Index(fields=['predecessor', 'dependency_type'], name='meeting_man_predece_444d9c_idx'),
        ),
        migrations.AddIndex(
            model_name='actiondependency',
            index=models.Index(fields=['successor', 'dependency_type'], name='meeting_man_success_47f014_idx'),
        ),
        migrations.AddConstraint(
            model_name='actiondependency',
            constraint=models.UniqueConstraint(fields=('predecessor', 'successor', 'dependency_type'), name='mm_unique_action_dependency'),
        ),
        migrations.AddConstraint(
            model_name='actiondependency',
            constraint=models.CheckConstraint(condition=models.Q(('predecessor', models.F('successor')), _negated=True), name='mm_no_self_action_dependency'),
        ),
        migrations.AddIndex(
            model_name='actiondeadlinechangerequest',
            index=models.Index(fields=['status', 'requested_due_date'], name='meeting_man_status_f2b621_idx'),
        ),
        migrations.AddIndex(
            model_name='actiondeadlinechangerequest',
            index=models.Index(fields=['requested_by', 'status'], name='meeting_man_request_abce31_idx'),
        ),
        migrations.AddIndex(
            model_name='actioncompletionsubmission',
            index=models.Index(fields=['status', 'submitted_at'], name='meeting_man_status_b40a65_idx'),
        ),
        migrations.AddIndex(
            model_name='actioncompletionsubmission',
            index=models.Index(fields=['reviewed_by', 'status'], name='meeting_man_reviewe_c60561_idx'),
        ),
        migrations.AddConstraint(
            model_name='resolutionactionroleassignment',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('unit__isnull', False), _connector='OR'), name='mm_action_role_has_user_or_unit'),
        ),
        migrations.AddConstraint(
            model_name='resolutionactionroleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('user__isnull', False)), fields=('action', 'role', 'user'), name='mm_unique_active_action_user_role'),
        ),
        migrations.AddConstraint(
            model_name='resolutionactionroleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('unit__isnull', False)), fields=('action', 'role', 'unit'), name='mm_unique_active_action_unit_role'),
        ),
    ]
